### PR TITLE
NuPogodi patch 19.05.2012

### LINKED ISSUE #166: NuPogodi patch: How to integrate?
Hi,

here @NuPogodi published a patch: http://www.mobileread.com/forums/showpost.php?p=2080025&postcount=380
It has some nice things, however, it's not easy to separate the new functionality and I'm having a hard time figuring out how to integrate it... Ideas?

### PR DESCRIPTION
**Pull request by dpavlin**
http://www.mobileread.com/forums/showpost.php?p=2086299&postcount=413

@NuPogodi seems to find github too hard to use, so I took latest patch provided on forum.

As opposed to last version, it at least have proper attribution. We can hopefully close #166 after this is merged.

### CODE REVIEW

**Comment by houqp** [comment]
Ready to merge?

**Comment by ghost** [comment]
I've just uploaded a bit corrected version of filechooser.lua. Now it can call helppage (list of hotkeys). That's the only difference to the version I've uploaded yesterday (19.05.12).

**Comment by houqp** [comment]
@NuPogodi, go send the pull request :)

**Comment by dpavlin** [comment]
@NuPogodi sorry to bother you again with git, but you would need to continue developing based on our master branch instead of yours which diverged from current version.

I would recommend that you backup your changes in new branch and pull new master branch using:

```
git checkout -b improvements # this will backup current master branch to new improvement branch
git branch -D master # remove current master branch
git checkout -b master origin/master # checkout clean master
```

After that, you can do `diff improvements` to see why I'm suggesting such approach :-(

As a help, few git tips:
- you can apply single commit from your branch using `git cherry-pick sha1-hash-of commit` (which is why it's good that commits are small changes)
- if you have more than one change which you would like to commit as separate commits (grouping features together) you can use `git add -p path/to/file` which will ask you if you want to include each chunk of changes. After that do `git commit` (without path) and that will commit staged changes from `git add -p`
- you can review last commit with `git show` and if you are not happy `git add` or `git rm` changes and modify last commit with `git commit --amend`
- you can always update to current upstream master (from @hwhw's repo) using `git pull origin master`

I would really suggest to commit smaller changes (this feature works, let's commit it) because it will make integrating your changes much easier.

Hope this helps.

**Pull request merged**
