### PR TITLE
Bugfixes for typos in last pull request

### PR DESCRIPTION
**Pull request by ghost**
1. restored: own font 'infofont' for messages & warnings
2. fixed: typo that caused helppage to crash

### CODE REVIEW

**Comment by dpavlin** [comment]
I had to merge this request to master manually because of conflict, but now commit 6c9fb8b023ef48670c6dce29892bd5a64e89d205 looks correct :-)

Thanks @NuPogodi for all your hard work it's really appreciated.

**Comment by dpavlin** [comment]
Unfortinatly now it dies with

```
# # InfoMessage  Registering fonts... 1
# #! Font infofont (./fonts/infofont) not supported: freetype error
lua config error: ./widget.lua:108: attempt to index field 'face' (a nil value)
```

**Comment by houqp** [comment]
OK, I found out the cause of the crash. It is in `settings.reader.lua`. So if you start with a fresh setting file, everything should go right. But in my old setting file, I have:

``` lua
    ["fontmap"] = {
        ["hfont"] = "droid/DroidSans.ttf",
        ["infont"] = "droid/DroidSansMono.ttf",
        ["scfont"] = "droid/DroidSansMono.ttf",
        ["tfont"] = "NimbusSanL-BoldItal.cff",
        ["rifont"] = "droid/DroidSans.ttf",
        ["ffont"] = "droid/DroidSans.ttf",
        ["cfont"] = "droid/DroidSansFallback.ttf",
        ["pgfont"] = "droid/DroidSans.ttf",
        ["hpkfont"] = "droid/DroidSansMono.ttf"
    },
```

This over-write the fontmap table in font module. So it hides infofont and adds pgfont. Given that many other users might also have similar settings files like me, we need to handle the `fontmap` section specially while reading `settings.reader.lua`. I think the same goes for other setting sections with subtables.

**Comment by ghost** [comment]
Ohhh, my bad... I did tested the filemanager (^+P+D), but not run the reader directly (^+P+P). The former runs smoothly (the messages are really rendered with 'infofont'), while the latter crashes. ATM, I have no other suggestion than the reader try to show message (now with infofont), but Font.fontmap (or FreeType) is not yet defined. One has to check the sequence of commands in reader.lua

**Comment by houqp** [comment]
Um.. Maybe we can fix it in this way:

Currently, what we does for reading fontmap config is:

``` lua
fontmap = G_reader_settings:readSetting("fontmap")
```

A quick dirty workaround can be:

``` lua
fontmap = G_reader_settings:readSetting("fontmap")
if fontmap ~= nil then
    for ftname, face in ipairs(fontmap) do
        if Font.fontmap[ftname] then
            Font.fontmap[ftname] = face
        end
    end
end
```

This make sure we do a entry by entry update. Maybe someone can come up with a better solution.

**Comment by dpavlin** [comment]
@houqp you are fast. I'm coding more-or-less same thing right now :-)

**Comment by dpavlin** [comment]
I will close this pull request and if you agree with fix, @houqp can merge it to master :-)

**Pull request closed without merging**
