### PR TITLE
separates configurable options from the code

### PR DESCRIPTION
**Pull request by kai771**
I preffer different set of defaults than those shipped with KPV. Those defaults are contained in unireader.lua, where 99% of develpment takes place, so I'd have to manually edit it every time. This moves those options to unireader_h.lua, which doesn't have to be changed.

### CODE REVIEW

**Comment by tigran123** [comment]
I have no objection to the symbolic defines for the defaults that you are proposing, but I object to separating the object definition (UniReader = {....}) and its methods (UniReader:functions()) into different source files. It is very convenient to have them in the same file and this is done for all other objects in KPV source code. So, please leave UniReader object alone in the unireader.lua but move the defaults into a separate defaults.lua file. It is not really specific to unireader so it shouldn't be called unireader_h.lua.

Btw, I agree that unireader.lua is growing too big --- perhaps we should consider moving utility (i.e. not object methods) functions out of it into separate source files.

**Comment by hwhw** [comment]
I tend to agree to @tigran123. unireader.lua is bloated, but with features, unfortunately. Things to abstract out would probably be the "alternative navigation" modes.

In the new_ui branch, I seperated functionality into "sub-modules" to a reader object. I'm not sure yet if that's the last word there, either. But it makes an interesting approach. It won't be easy to trim that jungle of unireader.lua down to a nice park...

**Comment by kai771** [comment]
@tigran123 The initial commit was just a quick, lazy cut-and-paste. I agree with all your suggestions and will change it shortly.

**Comment by dracodoc** [comment]
I suggest similar things before on #261. And the config file better compatible with most version upgrades so user can just keep his config file and keep all his settings upon upgrade.

**Comment by kai771** [comment]
Adds background_color to defaults, as requested in #261 (dracodoc called it "margin color", but I think "background color" is more suitable).

**Comment by houqp** [comment]
looks nice now, ready to merge?

**Comment by kai771** [comment]
As far as I'm concerned, it is, but you better ask someone more knowledgeable. :)

**Comment by houqp** [comment]
OK, I will leave it to other developers :)

**Comment by tigran123** [comment]
Looks fine to me.

**Pull request merged**
