### PR TITLE
Jump history in crereader loses the last position.

### PR DESCRIPTION
**Pull request by tigran123**
This is a fix for the issue #331.

Note that although the pull request seems to contain four commits this is merely because I accidentally merged @dpavlin 's twocolumn fixes in my local master branch. However, the actual changes contained in this pull request only affect crereader.lua i.e. have nothing to do with @dpavlin 's changes. Next time I will be more careful when switching between local and remote branches...

### CODE REVIEW

**Comment by houqp** [comment]
Just leave here two tips for git usage :)
- when doing `pull` or `merge` operations, passing `--rebase` argument will make the commit log cleaner. i.e. you won't see logs like `Merge remote-tracking branch .... blablalba`.
- usually when I want to test commits that is not merged into the master branch, I prefer to create a temporary testing branch and merge all the commits in there. So I can still keep a clean master that I can use to send pull request during the test.

**Comment by tigran123** [comment]
@houqp Thank you for the tip about --rebase. Concerning the second item, yes, that is exactly how I worked as well. It is just for the crereader fix I completely forgot that my current branch was the local dpavlin-column which corresponded to the remote dpavlin/two-column-recalculate-pan and so I edited and committed crereader.lua into it and then (accidentally) merged the whole thing into my local master. At that point I knew that it is best not to try to separate @dpavlin 's changes from my changes to crereader.lua but patiently wait until his pull request is merged and then send my own pull request.

So, yes, normally, I create a temporary branch and work in it.

**Comment by dpavlin** [comment]
@tigran123 this was not your mistake -- I rebased my changes on top of current master (that why commits disappeared after first message and appeared on bottom of issue) and since you already merged it in your branch they re-appeared in your pull request.

I didn't noticed that you are merging my changes, because in that case rebase is bad idea...

**Comment by dpavlin** [comment]
When you want to extract just a few commits from branch, `git cherry-pick sha1` is very helpful.

**Comment by tigran123** [comment]
@dpavlin Yes, someone may need to "git cherry-pick SHA1: 60af9c4244" from @NuPogodi 's master tree because he mixed his fixes with the new InfoMessage:inform stuff instead of placing the latter in a separate branch (assuming this change fixes the selectmenu font non-persistency I mentioned recently).

**Comment by tigran123** [comment]
@dpavlin Shall I do the cherry-picking?

**Comment by tigran123** [comment]
@dpavlin I take that back, his commits are spread "by file" instead of logically "by change", so it is very messy to have to pick things up because one has to split a commit into logical entities. I'll leave it to someone else to deal. The whole issue is no big deal anyway :) (and the fix is just 2-3 lines of code, so it is easier to just re-implement it manually, giving proper credit attribution to @NuPogodi in the commit header and pull request, of course).

**Pull request merged**
