### PR TITLE
K4 framebuffer support

### PR DESCRIPTION
**Pull request by houqp**

### CODE REVIEW

**Comment by hwhw** [comment]
pretty cool.

**Comment by hwhw** [comment]
I think I will eventually change the behaviour, though. I'd like to use a 4bpp blitbuffer in between rather than using the 8bpp framebuffer as scratch space for 4bpp data and then doing the conversion.

**Comment by houqp** [comment]
Go ahead :) I can help with the testing work.

**Comment by hwhw** [comment]
I think it can wait for now. There are probably much more important things. In fact, it might even be very efficient how it currently is - at least in terms of memory used :-)

**Pull request merged**
