### PR TITLE
Restored: partial screen refresh; Moved: djvu render mode to djvureader; Added: menu with zoom-modes

### PR DESCRIPTION
**Pull request by ghost**
1. Full screen resfresh (unireader): default value rcountmax=5 is restored; manual page refresh function (^R) is no more silent - before making full refresh, it allows user to define the value rcountmax
2. Zoom-mode (unireader): added hotkey 'M' that allows to call menu with all available zoom-modes; the function duplicates the zoom-mode selection via direct hotkeys (A,S,D,F,etc), but, imho, it makes the mode-choice more user-friendly; (crereader) since zooming has no relation to cre-documents, I've removed hotkey 'M' inherited from unireader;
3. Djvu's 'render_mode' (unireader & djvureader): since this parameter is related to djvu-documents only, the hotkey 'R' and the respective toggling function was moved from unireader to djvureader

### CODE REVIEW

**Comment by tigran123** [comment]
On the item 3. --- I have already moved it to djvureader.lua and implemented via menu, as you suggested. It is in my forked tree, as you can see. Should I put the changes into a separate branch and try to do a pull request as dpavlin explained?

**Comment by houqp** [comment]
I will merge this pull request now. @tigran123, can you do a pull after the merge and send your pull request?

**Comment by tigran123** [comment]
@houqp Ok, I will try (though I am not yet 100% comfortable with the instructions on how to do this, (e.g. switching back from a branch to my forked "master" tree), but until I try I won't find out if I run into troubles :)

**Comment by houqp** [comment]
Great, looking forward to your request :)

Since @NuPogodi 's commits have already been merged into hw's repo, you can just pull from this repo while in your master tree:

```
git pull upstream master
```

The above command assume that you have already added hw's repo as your remote repo and named `upsteam`:

```
git remote add upstream git://github.com/hwhw/kindlepdfviewer.git
```

**Comment by tigran123** [comment]
@houqp  Yes, I did all that (actually I did fetch, followed by merge instead of pull) and then edited djvureader.lua and did `git add djvureader.lua` but `git diff djvureader.lua` shows no changes, i.e. empty output. But my changes affect not only djvureader.lua but also djvu.c and unireader.lua.

**Comment by tigran123** [comment]
I am a bit stuck at the moment. Currently, my situation is like this:

```
$ git fetch upstream
$ git merge upstream/master
Already up-to-date.
```

However, the files djvureader.lua, djvu.c and unireader.lua looks exactly how I want them to be and they are DIFFERENT from the master copies in hwhw/kindlepdfviewer. So, what do I do next?

From instructions by @dpavlin I gather that I need to do the following:
1. Open a new issue, say it will be #N called "djvu mode menu"

2.

```
git checkout -b issue-N-djvu-mode-menu upstream/master
```
1. `git add -p djvureader.lua djvu.c unireader.lua`
2. `git commit --author tigran123 -m `djvu menu mode #N``
3. `git push hwhw djvu-menu-mode`

I am not sure if the above steps will not mess up my tree completely, so I am hesitating to follow them (I always hesitate to do something I don't fully understand). But if someone confirms that the above sequence is correct, then perhaps I will take the risk...

**Comment by houqp** [comment]
Changes in all the file you added will not be shown in diff command. Diff command only shows changes that are not tracked. To get the diff output from added files and latest commit, you can use command:

```
git diff HEAD --
```

Which `HEAD` refers to the latest commit and `--` refers to latest tracked status(i.e. includes files that added but not committed).

Since the files are DIFFERENT from the upstream repo, it means you have already applied your changes and have git tracked on them. You can just do a `git commit` to add the changes to a commit and finally `git push` to push to the remote repo.

**Comment by houqp** [comment]
One more note. You can always use `git status` to get the tracking information, which is very helpful. In your case, you should see your changed file in the `Changes to be committed` section.

**Comment by dpavlin** [comment]
@tigran123 sorry about confusion. I was trying to document one special case of extracting few changes from git tree.

Just hit pull request on your github master branch, which will open new issue with all code attached. It has to land into master somehow anyway, so it's better sooner than later :-)

**Comment by dpavlin** [comment]
@tigran123 source of confusion is that that git pull upstream master doesn't produce any modification?

This is because you where merging master step by step all the time. Those are black vertical arrows from hwhw's repo to yours on https://github.com/hwhw/kindlepdfviewer/network

Does this help at all?

**Comment by tigran123** [comment]
@dpavlin Ah, that is very very easy, I get it _eventually_! What I was worried about was 14 commits, but now I clicked on the "Files Changed" to see the diff and I see that it is all perfectly manageable, nothing to be afraid of! :)

Ok, all done now. Sorry about the delay. The only bit that is still escaping me is how to avoid including in a pull request some commit (like my change to the filechooser, see issue #240)

**Comment by tigran123** [comment]
@NuPogodi I have a question concerning your new zoom mode selection menu. If I press Shift-S I expect to be in "Zoom to content width" (according to helppage and the comments in unireader.lua), but pressing "M" I see that the current mode is "zoom to content width with panoraming". Likewise, if I go to "zoom to content width" via "M" menu, calling the menu again shows that I am in "zoom to content width with panoraming". Is this expected behaviour?

**Comment by ghost** [comment]
Look at the lua-code... ATM, only 8 (e.g. corresponding to hotkeys A,S,D,F & ^A,^S,^D,^F) of 11 modes enumerated in the zoom-menu do change the zoom-mode. The rest [ Items 1) Zoom by value, 8) Fit zoom to content width with panoraming and 9) Fit zoom to content height with panoraming] are forcibly blocked by condition "if not re or re==1 or re==8 or re==9 then". I still included included these items just to visualize which mode is active at the moment.
One may certainly remove this blocking, but I did not yet tested how it influence the reader properties. Alternatively, one may remove the menu items in menu itself.

**Comment by tigran123** [comment]
Actually, I noticed that condition (though admittedly not before my first comment, which I then deleted), but didn't spot the fact that the elements 0,7 and 8 correspond to the blocking condition on return values of 1,8 and 9. Ok, I understand now, thank you.

**Comment by tigran123** [comment]
Btw, @NuPogodi concerning the rcountmax value: now that it is user-configurable, wouldn't it be nice to have it saved/restored persistently across restarts of the viewer? I see the call to settings:readSetting("partial_refresh_count") which is supposed to load it on startup, but I don't see it being saved anywhere (and grepping the files I don't actually see the value of "partial_refresh_count" stored anywhere either).

**Comment by ghost** [comment]
Did you ever read TODO in issue#1?
 https://github.com/NuPogodi/kindlepdfviewer/commit/4bb8ef7f452ff50d0ad6d9b19ca87dfc27128790

In fact. I have added this feature (saving rcountmax to global settings is just one line) long before this commit / pull request, but not included it for the only reason: i must have enough time to test whether it belongs to global settings or to settings stored for each doc? 

Sat, 1 Sep 2012 16:46:16 -0700 от Tigran Aivazian notifications@github.com:

**Comment by tigran123** [comment]
@NuPogodi I have read your description only at the top of this pull request, but not on each individual commit, sorry.

Yesterday I asked myself the same question: is rcountmax global or local for each document? Strictly speaking, it is a parameter controlling the behaviour of the viewer, i.e. logically not connected to the specific document. However, in practice, for some documents, it seems, the value of rcountmax=0 is desirable, for others I see no problem with leaving it at the default value of 5.

Whatever you decide, please make the name of the settings parameter the same as the name of Lua variable, to make it easier to remember (and grep). I.e. rename this "partial_refresh_count" -> "rcountmax". If "rcountmax" is not good enough for user-visible settings, it is not good enough for Lua source. I think it is fine.

**Comment by ghost** [comment]
1. Ok, I'll rename "partial_refresh_count" -> "rcountmax" despite of my personal opinion that it's definitely not the first priority task: having GUI possibilities to change something, none (probably, except for expecially boring persons who are worth of such a punishment) will explore the reader settings text and compare it with Lua-sources.
2. I do tend to storing rcountmax among the global reader settings (valid for all readers - pdf, djvu & crengine). Of cause, one may add rcountmax to both setting files with the following priority (from min to max) default=5 > if any, rcountmax in global settings >  if any, rcountmax in document history file. But it seems me not rational to spend soo much efforts since the GUI-procedure to adjust rcountmax for each concrete document costs us just few seconds-
3. ATM, I'm somewhat busy, so I will probably delay my commits & the next pull request on one day or two.

Sun, 2 Sep 2012 02:31:46 -0700 от Tigran Aivazian notifications@github.com:

**Pull request merged**
