### PR TITLE
Bug fix & added simple TOC menu & bookmark support & notification widget

### PR DESCRIPTION
**Pull request by houqp**
Will add @tigran123 's advanced TOC later

### CODE REVIEW

**Comment by chrox** [comment]
Double tap on the right top corner of the screen makes KPV exit unexpectedly with debug info:

```
# {
    ["handler"] = "onGesture",
    ["args"] = {
        [1] = {
            ["pos"] = {
                ["y"] = 91,
                ["x"] = 513,
                ["h"] = 0,
                ["w"] = 0
            },
            ["ges"] = "double_tap"
        }
    }
}
lua config error: ./frontend/ui/widget.lua:669: attempt to index field 'dimen' (a nil value)
stack traceback:
    ./frontend/ui/widget.lua:669: in function 'paintTo'
    ./frontend/ui/ui.lua:160: in function 'run'
    ./reader.lua:113: in main chunk
```

And this happens when bookmarking all PDF and DJVU pages.

**Comment by houqp** [comment]
That's strange, I can't line 669 in widget.lua. Could you make sure you checked out to the right branch?

UPDATE: 

Ok, it turns out I forgot to commit that fix, now it should work

**Comment by chrox** [comment]
Now I reseted the current branch to hwhw's new_ui_code with `git reset --hard upstream/new_ui_code` and pulled your code with `git pull houqp-upstream new_ui_houqp`. In the emulator the error info comes like this:

```
# {
    ["handler"] = "onGesture",
    ["args"] = {
        [1] = {
            ["pos"] = {
                ["y"] = 76,
                ["x"] = 512,
                ["h"] = 0,
                ["w"] = 0
            },
            ["ges"] = "double_tap"
        }
    }
}
lua config error: ./frontend/ui/widget.lua:617: attempt to index field 'dimen' (a nil value)
stack traceback:
    ./frontend/ui/widget.lua:617: in function 'paintTo'
    ./frontend/ui/ui.lua:160: in function 'run'
    ./reader.lua:113: in main chunk
```

**Comment by chrox** [comment]
It works great with the patch c0602fb now. Thanks.

**Pull request merged**
