### PR TITLE
Memory usage configurable from lua

### LINKED ISSUE #80: cache size control for DJVU
Hi,

I just found that djvulibre also provides API for cache size control(starts from ddjvuapi.h line 220). Hope somebody can take a look and add a knob in our code.

### PR DESCRIPTION
**Pull request by dpavlin**
If this changes seem sane, we can close #80 but for #79 will need /proc/meminfo parsing in lua, which I still don't know how to write.

### CODE REVIEW

**Comment by houqp** [comment]
OMG, did I miss clicked close pull request? Can you send it again?

**Comment by houqp** [comment]
what kind of information do you want to get from /proc/meminfo ?

**Comment by dpavlin** [comment]
`grep MemFree: /proc/meminfo | cut -d: -f2 | sed 's/^ *//' | cut -d" " -f1` in lua :-)

**Comment by houqp** [comment]
then just do a `os.execute` ;P

**Comment by dpavlin** [comment]
I'm reluctant to os.execute because that involves using additional memory for shell and all little commands that get executed, so I would prefer to parse lines from lua so we can get more accurate number. I'm also thinking about using /proc/$pid/status to compare it with system's view of how much RAM we are using.

This might even allow to pre-cache more pages if we have spare memory.

**Pull request merged**
