### PR TITLE
make history dir in bootstrapemu target

### PR DESCRIPTION
**Pull request by houqp**

### CODE REVIEW

**Comment by kai771** [comment]
Unrelated to this, but... It seems you made a mistake and included me in koreader organization members :). It started giving me the option to merge pull requests in koreader.

**Comment by houqp** [comment]
nop, it's not a mistake ;p

I give full permissions to all members because I trust everyone :)

BTW, feel free to move librerator to koreader org if you want.

**Comment by kai771** [comment]
In that case, thank you very much for the honour, but please remove me all the same.

Edit: Nevermind, I found how to do it myself.

**Comment by houqp** [comment]
oops, sorry about that, I should ask you first before adding you as member ;p

**Comment by kai771** [comment]
No worries, all is good. :)

**Pull request merged**
