### PR TITLE
Info_timeout in emulator and defaults.lua clean-up

### PR DESCRIPTION
**Pull request by kai771**
Cleans up defaults.lua (removes some values that should not be set by the user) and introduces DINFO_TIMEOUT_FAST and DINFO_TIMEOUT_SLOW. All :inform() calls in unireader.lua that had nil as the timeout have DINFO_TIMEOUT_FAST now, and all other values (1000, 1500, 2000) have DINFO_TIMEOUT_SLOW. When run in emulator, :inform() will always use value set as DINFO_TIMEOUT_SLOW.

### CODE REVIEW

**Comment by tigran123** [comment]
Btw, this change made the Shift-X function slightly inconvenient in the emulator i.e. one has to either wait 1 second or press extra keys. Maybe for the Shift-X command handler we really should pass `nil` to those two calls to :inform() instead of DINFO_TIMEOUT_FAST?

Update: I see that just passing `nil` wouldn't be good enough. Ok, we may have to either call :show() method or (better) change the logic in dialog.lua to allow "really no timeout" setting.

**Comment by tigran123** [comment]
Also, you missed quite a few places that still have the hardcoded timeout value:

```
$ grep InfoMessage:inform *lua | grep 1500
crereader.lua:      InfoMessage:inform("No Table of Contents ", 1500, 1, MSG_WARN)
crereader.lua:              InfoMessage:inform("Page already marked ", 1500, 1, MSG_WARN)
crereader.lua:              InfoMessage:inform("Page marked ", 1500, 1, MSG_WARN)
filechooser.lua:        InfoMessage:inform("Folder can't be deleted! ", 1500, 1, MSG_ERROR,
$ grep InfoMessage:inform *lua | grep 1000
filechooser.lua:                InfoMessage:inform("File copied to clipboard ", 1000, 1, MSG_WARN,
inputbox.lua:                   InfoMessage:inform("No input! ", 1000, 1, MSG_WARN, "There is nothing to calculate")
inputbox.lua:                       InfoMessage:inform("Invalid input! ", 1000, 1, MSG_WARN)
koptconfig.lua: InfoMessage:inform("New page bbox ", 1000, 1, MSG_WARN, "New page bounding box")
pdfreader.lua:          InfoMessage:inform("No attachments found ", 1000, 1, MSG_WARN)
pdfreader.lua:      InfoMessage:inform("Failed to save attachments ", 1000, 1, MSG_WARN)
screen.lua: InfoMessage:inform(msg..string.format("%.2fs ", diff), 2000, 1, MSG_WARN, msg..math.ceil(diff*1000).." milliseconds")
$ grep InfoMessage:inform *lua | grep 2000
crereader.lua:      InfoMessage:inform("No jump history found ", 2000, 1, MSG_WARN)
crereader.lua:      InfoMessage:inform("No bookmark found ", 2000, 1, MSG_WARN)
crereader.lua:          InfoMessage:inform("Default document font set ", 2000, 1, MSG_WARN,
crereader.lua:              InfoMessage:inform("Already first jump ", 2000, 1, MSG_WARN)
crereader.lua:              InfoMessage:inform("Already last jump ", 2000, 1, MSG_WARN)
crereader.lua:      InfoMessage:inform( found.." hits '"..search.."' pos "..pos, 2000, 1, MSG_WARN)
crereader.lua:      InfoMessage:inform( "'"..search.."' not found in document ", 2000, 1, MSG_WARN)
filechooser.lua:    InfoMessage:inform("Unsupported function! ", 2000, 1, MSG_WARN,
filehistory.lua:                InfoMessage:inform("No search hits ", 2000, 1, MSG_WARN,
filehistory.lua:                InfoMessage:inform("File does not exist ", 2000, 1, MSG_ERROR)
filehistory.lua:        InfoMessage:inform("No reading history ", 2000, 1, MSG_WARN, "The reading history is empty!")
filesearcher.lua:                   InfoMessage:inform("No search hits ", 2000, 1, MSG_WARN,
reader.lua:             InfoMessage:inform(err:sub(1,30), 2000, 1, MSG_ERROR)
reader.lua:             InfoMessage:inform("Error opening document! ", 2000, 1, MSG_ERROR)
screen.lua: InfoMessage:inform(msg..string.format("%.2fs ", diff), 2000, 1, MSG_WARN, msg..math.ceil(diff*1000).." milliseconds")
```

**Comment by tigran123** [comment]
Oh, we also completely broke interactive stuff like "Press `Y` to confirm", so we'll need to redo this properly.

**Comment by kai771** [comment]
Yeah, I just did unireader.lua. Didn't even occur to me that other files needs checking. :(
Don't understand the second part - what interactive stuff?

**Comment by tigran123** [comment]
In filechooser.lua there is code like this:

```
InfoMessage:inform("Press 'Y' to confirm ",nil, 0, MSG_CONFIRM)
if ReturnKey() == KEY_Y then self:deleteFileAtPosition(pos) end
```

we can't just blindly change that nil to non-nil --- try it and see what happens :)

**Comment by tigran123** [comment]
The problem is that if we set the timeout to non-nil then the message will disappear, but we want it to stay on the screen until the user presses something.

**Comment by tigran123** [comment]
Ok, we can differentiate between `nil` and `0`, i.e. those places which really cannot have a non-nil timeout should pass 0. So, we need two values: DINFO_TIMEOUT_FAST and DINFO_TIMEOUT_ZERO and only the first one should be delayed on the emulator, the other one should be allowed to go through with no delay.

**Comment by kai771** [comment]
Should be fixed with #567.

**Pull request merged**
