### PR TITLE
Multi-level TOC support.

### PR DESCRIPTION
**Pull request by tigran123**
The need for multi-level Table of Contents (aka "outline" and "PDF bookmarks") was raised in #235.
Now I have implemented it and tested on a variety of PDF and DjVu files (and even FB2 files).

### CODE REVIEW

**Comment by tigran123** [comment]
Actually, before you apply this, please wait for me to commit the change to selectmenu to allow a variant of choose() method which does not refresh the header. This would avoid irritating header redraws on expand/collapse requests.

**Comment by tigran123** [comment]
No, ignore my previous comment. Please apply the pull request "as is", because if we don't do a full refresh in selectmenu, then the screen will get very messy, i.e. there will be ghosts on the screen.

**Comment by houqp** [comment]
awesome patch! It's really handy :)

**Comment by tigran123** [comment]
Thank you! :)

**Pull request merged**
