### PR TITLE
Touch gesture detection module

### PR DESCRIPTION
**Pull request by houqp**
I am lazy, so I just copied the design from Firefox OS:

https://github.com/mozilla-b2g/gaia/blob/master/shared/js/gesture_detector.js

Basically it's just state machine. State is changed according to the touch input. 

I added a scheduler in inputevent.lua module so sorry that we have two scheduler now (another in ui.lua). Because I need to simulate the setTimeOut function in Javascript during the gesture detection, so this is the only way I can think of so far. Maybe we can clean it up later. Also to help with the detection and scheduling, I also added a time.lua module which abstract the operations on time values.

Currently, only single tap, double tap and hold gesture is supported. Since single tap is enough to handle most of the operations we need during reading, I decide to stop developing for new gestures but switch back to more important part of the reader.

If you want to test it but you don't have kindle Touch, you can try it in emulator. Mouse click is translated into touch events.

Of course this is just one possible solution for touch support, feel free to come up with any better implementation :)

### CODE REVIEW

**Comment by chrox** [comment]
Gesture detect doesn't work on Kindle Paperwhite. Debug output says:

```
# in tap state... {
    ["y"] = 149,
    ["timev"] = {
        ["usec"] = 157818,
        ["sec"] = 1338511480
    }
}
# in tap state... {
    ["timev"] = {
        ["usec"] = 193437,
        ["sec"] = 1338511480
    },
    ["id"] = -1
}
# set up tap timer
```

But in emulator it seems working well.

**Comment by houqp** [comment]
um, that's strange, so bad that I cannot test it on real device :(

The first dirty implementation did work though, I managed to select a book and did some page turns in my KP before. This is the re-write, and if the touch event from kernel is not changed, it should work as before...

And it's pretty strange that we only get y coordinate in first event... When you have time, could you try dump all the events from kernel in gesturedetector.lua? (just uncomment this line: https://github.com/houqp/kindlepdfviewer/blob/ges-detect/frontend/ui/gesturedetector.lua#L75) Given the exact event, I should be able to reproduce it in emulator.

**Comment by chrox** [comment]
This is the whole output after I run `./reader.lua -d ../documents` from the ssh terminal and taped on the file manager screen. I also uncommented the line `DEBUG(ev.type, ev.code, ev.value, ev.time)` in `gesturedetector.lua`.

```
Auto-detected Kindle PaperWhite
Hardware    : Amazon.com MX50 YOSHIME Board
# 3 57 0 {
    ["usec"] = 961462,
    ["sec"] = 1338515519
}
# 3 53 461 {
    ["usec"] = 961517,
    ["sec"] = 1338515519
}
# 3 54 122 {
    ["usec"] = 961531,
    ["sec"] = 1338515519
}
# 0 0 0 {
    ["usec"] = 962081,
    ["sec"] = 1338515519
}
# in tap state... {
    ["y"] = 122,
    ["x"] = 461,
    ["timev"] = {
        ["usec"] = 962081,
        ["sec"] = 1338515519
    },
    ["id"] = 0
}
# set up hold timer
# 3 57 -1 {
    ["usec"] = 80857,
    ["sec"] = 1338515520
}
# 0 0 0 {
    ["usec"] = 81027,
    ["sec"] = 1338515520
}
# in tap state... {
    ["timev"] = {
        ["usec"] = 81027,
        ["sec"] = 1338515520
    },
    ["id"] = -1
}
# set up tap timer

```

**Comment by chrox** [comment]
And double tap output is like this:

```
# 3 57 0 {
    ["usec"] = 707296,
    ["sec"] = 1338516048
}
# 3 53 502 {
    ["usec"] = 707311,
    ["sec"] = 1338516048
}
# 3 54 429 {
    ["usec"] = 707314,
    ["sec"] = 1338516048
}
# 0 0 0 {
    ["usec"] = 707479,
    ["sec"] = 1338516048
}
# in tap state... {
    ["y"] = 429,
    ["x"] = 502,
    ["timev"] = {
        ["usec"] = 707479,
        ["sec"] = 1338516048
    },
    ["id"] = 0
}
# set up hold timer
# 3 53 503 {
    ["usec"] = 747047,
    ["sec"] = 1338516048
}
# 0 0 0 {
    ["usec"] = 747062,
    ["sec"] = 1338516048
}
# in tap state... {
    ["timev"] = {
        ["usec"] = 747062,
        ["sec"] = 1338516048
    },
    ["x"] = 503
}
# 3 57 -1 {
    ["usec"] = 782413,
    ["sec"] = 1338516048
}
# 0 0 0 {
    ["usec"] = 782557,
    ["sec"] = 1338516048
}
# in tap state... {
    ["timev"] = {
        ["usec"] = 782557,
        ["sec"] = 1338516048
    },
    ["id"] = -1
}
# set up tap timer
# 3 57 0 {
    ["usec"] = 884701,
    ["sec"] = 1338516048
}
# 3 53 512 {
    ["usec"] = 884715,
    ["sec"] = 1338516048
}
# 3 54 437 {
    ["usec"] = 884717,
    ["sec"] = 1338516048
}
# 0 0 0 {
    ["usec"] = 884867,
    ["sec"] = 1338516048
}
# in tap state... {
    ["y"] = 437,
    ["x"] = 512,
    ["timev"] = {
        ["usec"] = 884867,
        ["sec"] = 1338516048
    },
    ["id"] = 0
}
# set up hold timer
# 3 53 513 {
    ["usec"] = 924463,
    ["sec"] = 1338516048
}
# 0 0 0 {
    ["usec"] = 924478,
    ["sec"] = 1338516048
}
# in tap state... {
    ["timev"] = {
        ["usec"] = 924478,
        ["sec"] = 1338516048
    },
    ["x"] = 513
}
# 3 57 -1 {
    ["usec"] = 982021,
    ["sec"] = 1338516048
}
# 0 0 0 {
    ["usec"] = 982180,
    ["sec"] = 1338516048
}
# in tap state... {
    ["timev"] = {
        ["usec"] = 982180,
        ["sec"] = 1338516048
    },
    ["id"] = -1
}
# {
    ["handler"] = "onGesture",
    ["args"] = {
        [1] = {
            ["pos"] = {
                ["y"] = 437,
                ["h"] = 0,
                ["x"] = 512,
                ["w"] = 0
            },
            ["ges"] = "double_tap"
        }
    }
}

```

**Comment by chrox** [comment]
And hold gesture event is:

```
# 3 57 0 {
    ["usec"] = 794761,
    ["sec"] = 1338516189
}
# 3 53 493 {
    ["usec"] = 794776,
    ["sec"] = 1338516189
}
# 3 54 450 {
    ["usec"] = 794779,
    ["sec"] = 1338516189
}
# 0 0 0 {
    ["usec"] = 794948,
    ["sec"] = 1338516189
}
# in tap state... {
    ["y"] = 450,
    ["x"] = 493,
    ["timev"] = {
        ["usec"] = 794948,
        ["sec"] = 1338516189
    },
    ["id"] = 0
}
# set up hold timer
# 3 54 451 {
    ["usec"] = 953254,
    ["sec"] = 1338516189
}
# 0 0 0 {
    ["usec"] = 953268,
    ["sec"] = 1338516189
}
# in tap state... {
    ["y"] = 451,
    ["timev"] = {
        ["usec"] = 953268,
        ["sec"] = 1338516189
    }
}
# 3 57 -1 {
    ["usec"] = 315012,
    ["sec"] = 1338516190
}
# 0 0 0 {
    ["usec"] = 315180,
    ["sec"] = 1338516190
}
# in tap state... {
    ["timev"] = {
        ["usec"] = 315180,
        ["sec"] = 1338516190
    },
    ["id"] = -1
}
# set up tap timer
```

**Comment by houqp** [comment]
OK, double tap is correctly generated... Can you talk in gtalk? I have heard that the access to Gmail is very unstable in China recently. Or do you prefer other chat client? It might be easier to debug if we can chat in real time ;p

**Comment by chrox** [comment]
OK. Of course.

**Comment by houqp** [comment]
OK, @chrox and I find out the bug :) The touch detection is working in real kindle now.

**Comment by chrox** [comment]
Patch of this bug is in #636.

**Comment by chrox** [comment]
Basic touch gestures are tested working on Kindle paperwhite now. This PR could be merged.

**Comment by houqp** [comment]
OK, I will leave it here one more day for review, if there is no objection, especially @hwhw, I will merge it ;p

**Comment by th0mass** [comment]
Wow! Does this whole thing means that Touch version is coming? :+1:

**Comment by chrox** [comment]
@th0mass Generally, yes, but it's still far away from a public release.

**Comment by houqp** [comment]
@th0mass yes, if we have more developers ;p

merging now since no objection...

**Comment by th0mass** [comment]
@houqp I wish I could help.

**Pull request merged**
