### PR TITLE
add usedbbox support

### PR DESCRIPTION
**Pull request by houqp**
now the fit to content mode is still incomplete, i.e. we cannot move the view around inside one page. will handle this in next pull request.

### CODE REVIEW

**Comment by houqp** [comment]
OK, now full support for pageturn by view for all modes! One more step towards the first usable release :)

I am somehow amazed by the flexibility of the new framework. I wrote far less, and more readable, code to implement this feature.

**Comment by chrox** [comment]
Great news. I will test it later.

**Comment by chrox** [comment]
@houqp It works fine in Kpw after fixing the `zoom_mode` bug. I leave the fixing work to you as it will conflict with my fixing without merging your PR. :)

**Comment by houqp** [comment]
fix attached, see if it works for you :)

**Comment by chrox** [comment]
Tested in KP and in emulator. I works as expected. But I found another bug that is not relevant with this PR that document opened with crereader is not responsive to gesture page tuning neither in Kp nor in emulator.

**Comment by houqp** [comment]
OK, I will look into that later :)

**Comment by houqp** [comment]
patch included in new PR ;p

**Pull request merged**
