### PR TITLE
recalculate font size for each link

### PR DESCRIPTION
**Pull request by dpavlin**
This fixes problems with pages full of links where first link
is so big that rest of link shotcuts overlap on page #385

### CODE REVIEW

**Comment by dpavlin** [comment]
don't merge this one yet. -2 should be after globalzoom

**Comment by tigran123** [comment]
Tested --- works.

Update: tested on Zak.pdf fine, but on Stephens.pdf it is still not good if you define bbox around the text on the first Index page and then do `Shift-S` followed by `L` --- the index shortcuts are still too big (probably that is what you meant by "-2 should be after globalzoom"

**Comment by tigran123** [comment]
Even with the latest patches the links on the file Stephents.pdf are too big.

**Comment by tigran123** [comment]
Also, if you just position the screen in the middle of the Index page and then `Alt-Next` to zooom in a few times, then press `L` --- the shortcuts are awfully big and no way to tell which link each of them belongs to.

**Comment by dpavlin** [comment]
I totally missed fact that I'm using globalzoom wrong. Since result is already in pixels I don't need to multiply it with zoom.

I would love to see some kind of hungarian notation of pixels and document points (maybe with `*_px` or `*_pt`) to prevent mistakes like this. It totally not obvious when looking in code if variables contain pixels of document points.

**Comment by dpavlin** [comment]
Can we merge this?  d14d0ba is quite important fix, because all link targets are wrong if page has urls

**Comment by tigran123** [comment]
The last time I checked the font sizes were still wrong (i.e. huge shortcuts obscuring the smaller ones). But if you changed something since then, then I'll retest it cleanly, but not today (it is almost midnight here) --- tomorrow morning. Or someone else can test it today, if it is urgent.

**Comment by tigran123** [comment]
Ah, I just noticed that your commits were AFTER my comment, in fact a WHOLE DAY after! Sorry :)
I thought they were BEFORE!

**Comment by tigran123** [comment]
Tested now --- works fine, merging...

**Pull request merged**
