### PR TITLE
KUAL extensions

### PR DESCRIPTION
**Pull request by twobob**
KUAL extensions added (since kindlepdfviewer will soon support all devices)
Added README.txt with helpful links to this extensions package.

Support notes thread here http://www.mobileread.com/forums/showpost.php?p=2414040&postcount=5

### CODE REVIEW

**Comment by twobob** [comment]
On a touch device on the current kindlepdfviewer-nightly-20130209 nightly build this would result in a harmless, benign, silent fail.

``` shell
[root@kindle kpdf]# bin/kpdf.sh 
bin/kpdf.sh: line 4: can't create /proc/keypad: nonexistent directory
bin/kpdf.sh: line 5: can't create /proc/fiveway: nonexistent directory
lua config error: ./reader.lua:119: only 4bpp is supported for now, got 8 bpp
Segmentation fault
/dev/loop/4 /mnt/us/kindlepdfviewer/fonts/host cramfs ro,noatime,nodiratime 0 0
lipc-wait-event exited with status 15.
lipc-wait-event terminated by signal: 15.
```

Other devices should work OOTB. Once underlying core support is in place the extension should "just work".

**Comment by tigran123** [comment]
Thank you. Is there any reason why you use the old version of kpdf.sh with all that killall lipc\* and cat crash.log etc? Doesn't the new way (via popen_noshell) work with KUAL? Just curious...

**Comment by twobob** [comment]
" tigran123 commented 4 hours ago
Thank you. Is there any reason why you use the old version of kpdf.sh with all that killall lipc\* and cat crash.log etc? Doesn't the new way (via popen_noshell) work with KUAL? Just curious..."

Not at all. It's purely an oversight, and in retrospect would be better reworked as simply a link to the /mnt/us/kindlepdfviewer/kpdf.sh I think?

**Comment by twobob** [comment]
Scratch this then. I'll rebase and do an internally dependent version. Raise another pull when I'm done yeah?

**Comment by tigran123** [comment]
In the source tree sym links are OK, because the development system is Linux with ext4 filesystem, but on the target Kindle the fs is VFAT which has no concept of symbolic links.

**Comment by twobob** [comment]
yep. understood. this will be a shell call direct the the relevant script.

Won't be affected :)

**Comment by houqp** [comment]
@twobob , will you send another PR to add KUAL support?

**Comment by twobob** [comment]
yep. was beavering away on testing the touch stuff as I really want this to do all devices.

Will raise PR ASAP

**Pull request closed without merging**
