### PR TITLE
issue #55 and help page

### PR DESCRIPTION
**Pull request by traycold**
Completed the refactoring of input loop of unireader, removing all `if..elseif..end`.
With this commit, every command is defined autonomously, and stored into a table. At the moment the info for every command are:
- shortcut (in case, with modifier);
- help message (description of command);
- function to call when shortcut is clicked.

As a bonus-feature of this refactoring, a help page when reader is active has been implemented (shortcut: H), that lists all defined shortcuts and the description (help message).

Of course, the table with all commands data could be the base for a future menu-based user-interface.

### CODE REVIEW

**Comment by houqp** [comment]
Great. 

I rewrote the font module in this commit some days ago:
https://github.com/hwhw/kindlepdfviewer/commit/f95231d789ad33cbbd5e8e257ecfc36cf75df14f

Now every UI does not need to define its own face as all faces are cached in font.lua globaly. Faces and hash can be fetched by `Font:getFaceAndHash(size, font)`.

**Comment by houqp** [comment]
Also remember to take a look at the coding styles, especially the function naming :) #62

I hope this can be merged soon so I can get my hands dirty with new features

**Comment by traycold** [comment]
> I rewrote the font module in this commit some days ago:

and 

> Also remember to take a look at the coding styles, especially the function naming :) #62

@houqp: now that I already asked for a pull request, I suppose that in case I want to make modification (to comply with coding styles and update font support, for example) I should either cancel my pull request, make the modification and issue a new pull request, or just make the modification and issue a second pull request on top of previous one, correct?

**Comment by houqp** [comment]
@traycold  You can just simply push to your own repo, this pull request will be automatically updated to the latest commit in your repo :) 

So far, seems that we can only fire up one pull request at a time.

**Comment by traycold** [comment]
ok, I will do this way as soon as possible (probably, this evening)

**Comment by traycold** [comment]
hi guys, I also renamed most of function names using camelCase, and also used font module by @houqp for helppage.

**Comment by hwhw** [comment]
I would say - merge it? if bugs occur, we can flesh them out afterwards. Or did I oversee something?

**Comment by traycold** [comment]
hi all, please have a look at description I used for the shortcuts. Maybe the messages I used to describe some of the features could be improved (I confess, I didn't try all of the features you introduced ;-) ).
In any case, I will also try to do the same next days.

**Pull request merged**
