### PR TITLE
Bunch of Makefile fixes

### PR DESCRIPTION
**Pull request by NiLuJe**
As promised & discussed, this should fix #341, #359 and #357 ;).

### CODE REVIEW

**Comment by tigran123** [comment]
Cool, let me test it and get back to you.

**Comment by tigran123** [comment]
Yes, perfect --- it works fine with the latest 2012.03 TC from CS/MG. However, before merging I would like confirmation of @dpavlin and @houqp as this would possibly require them to upgrade their TC as well. Are you guys ok with this? This would mean we are all "on the same page", so to speak, i.e. using the same build environment. I think there is definite benefit to be gained from it. And thanks to @NiLuJe who fearlessly fought with all the nasty alignments and make issues and won at the end! :) Thanks also to @kai771 who initiated the whole idea of moving to the latest TC!

PS. Btw, DjVu paging seems incredibly fast now... Hmmm, I should measure the timings properly before making such statements but it may be that the new way of building djvulibre did make some difference...

**Comment by NiLuJe** [comment]
I actually forgot to check if it fixed the PDF issues with the old GCC 4.2/glibc 2.5 TC...

Will do, because I'm intrigued...

@tigran123: I think djvulibre forces -O3, possibly crengine too. I didn't delve into autotools/cmake to check, and since it didn't mangle the rest of the CFLAGS, I'm trusting upstream knows what it's doing ;).

**Comment by tigran123** [comment]
Well, if @dpavlin and @houqp agree to move to 2012.03 TC then there is no need :)
Let's wait what they say...

But there is no harm to check of course, especially if you are intrigued.

**Comment by tigran123** [comment]
Also, if we all agree to move to 2012.03 TC then @kai771 can remove the "Controversial part" of his Development Guide, which may attract more developers (hopefully) as it would be crystal clear that we are not doing anything dodgy or breaking anyone's licenses...

**Comment by NiLuJe** [comment]
Hmm, it's working, but with the same kind of issues on FW 2.x as with a GCC 4.7 w/ unaligned access TC... Except it's GCC 4.2, so we can't do a thing about it. That's weird. Will do a few checks.

**Comment by NiLuJe** [comment]
Yup, -mno-unaligned-access correctly 'fixes' these issues on my own Linaro TC (which is still 'broken' in the sense that it still defaults to -munaligned-access, so a good testcase for this), but I'm afraid there's not much we can do about it on the old TC, so, yeah, while it might appear to work, I'd still recommend updating ;).

**Comment by NiLuJe** [comment]
Huh. The alignment trap doesn't increment/complain, but switching it to fixup instead of ignore does fix the issues. I'm stumped o_O.

**Comment by tigran123** [comment]
Great, let's hope that @dpavlin and @houqp hear you. I am all for upgrading. Now (after the release, i.e. long before the next release) is the _ideal_ time for such things --- leaves us plenty of time to test everything thoroughly...

**Comment by NiLuJe** [comment]
Okay, scratch my three previous messages. It's a random issue I'm seeing only on FW 2.x, every other kpdf launch, regardless of the TC used, and mostly unrelated to the unaligned accesses thing.

I'm checking with a MG build, just in case, and with my K2 in a slightly less custom state, but basically: apparently still works with the old TC.

**Comment by tigran123** [comment]
With FW 3.4 I see no issues whatsoever. And djvu (both opening and paging) definitely seems a bit faster (I am just too lazy to downgrade and compare the timings accurately :)

**Comment by dpavlin** [comment]
I'm all for moving to newer toolchain, so if you are happy with this changes I would love to see it merged.

**Comment by tigran123** [comment]
Yes, I tested them and even provided the build for the public in my "developer's build" area.
Ok, merging now. (let's hope @houqp doesn't mind :)

**Comment by tigran123** [comment]
Or shall we wait for @houqp confirmation? I would hate to upset him...

**Comment by NiLuJe** [comment]
Okay! False alarm. It appears to be a bad interaction with the specific Fonts/Settings I'm using on my K2 with the Fonts Hack and/or me being cheap and running kpdfview manually instead of relying on the launcher.

Can't reproduce it anymore via the launcher, after having killed the fonts hack.

That was starting to drive me mad. :D

(FWIW, the issue was broken screensaver behaviour every other launch: the 'Going to screensaver...' popup appearing on top of the screensaver (and staying there!) and not on top of the currently viewed item, and resuming to the screensaver instead of the last viewed page/item).

And it appears to still be working with every binaries (MG/old/mine).

And, yep, the MG binary does appear to be slightly snappier.

And I need to finish a sentence without the word 'appear' in it, so, there :D.

**Comment by tigran123** [comment]
You are still developing on K2??? :)
I also still like my old good Hanlin V3 (though I gave away as gifts almost all devices, keeping just one as a "memento" :), but I doubt I would ever bother developing on it again (btw, @houqp said he referred to my little libdjvu for Hanlin V3 while writing djvu support in KPV, so it wasn't a waste of time after all :)

**Comment by NiLuJe** [comment]
@tigran123 : Well, I mostly try not to break anything on it when I change stuff ;). For what I'm usually doing, it's fairly similar to the K3, so that's usually not a hassle to keep supporting ;).

It was also my first Kindle/eReader, so that may come into the equation ^^.

**Comment by dpavlin** [comment]
FWIW, I think it's important to support older devices because rooting kindle to install software is big enough hurdle to pass for most Kindle users, so we don't want to drop them off.

AFAIK, from software perspective K2 is on same software version as DXG so supporting it shouldn't be hard (I've seen only one K2 and nowdays it's at 3.x software, so I really can't check that claim :-)

**Comment by NiLuJe** [comment]
@dpavlin : Yep, the DX/DXG uses the exact same software as the K2 ;).

**Comment by houqp** [comment]
Oh, I just got up ;p Missed a long conversation. I would like to have my TC updated too and it will be better if all of us use the same one. :) 

merging for now.

**Comment by tigran123** [comment]
@houqp Great, thank you!

**Comment by NiLuJe** [comment]
@houqp : Well, to be perfectly honest, it was pretty much mostly me rambling to myself and running in circles because of a stupid oversight ^^.

**Pull request merged**
