### PR TITLE
crengine link support

### PR DESCRIPTION
**Pull request by dpavlin**
This is pull request from individual commits. This is not ready for merge.

I would welcome review of my C++ code so I'm submitting this as-is.

### CODE REVIEW

**Comment by tigran123** [comment]
I see that footnotes are also treated --- excellent! This was one of the major items on my list of crengine's useability mentioned in #320.

However, when I tested it I see that I cannot go back via `Back` if I follow a shortcut to the footnote in an fb2 file. Pressing `Back` just gives "Already first jump" message, so looks like it is not added to the jump history list.

Oh, and a more serious bug --- closing an fb2 book, exiting KPV and then starting it again and re-opening the same fb2 book via History caused the kpdfview address space to grow to 8.5GB with RSS of 6.3GB forcing my machine (with only 8GB physical RAM) to swap heavily, so I had to login via ssh from the netbook and kill -9 the kpdfview process. The book is Herodotus' History (in Russian) which has a lot of footnotes, here it is (I can't remember where I got it from, probably lib.rus.ec):

https://github.com/downloads/tigran123/libdjvu/Gerodot-Istorija.fb2.zip

**Comment by dpavlin** [comment]
Footnotes are really not my improvement - if they are links in original document crengine will support it.

I added origin point to history, but can't reproduce problem with fb2. I recently moved to x86_64 system so I think that our configuration are similar enough. OOH, I don't think I could fix that anyway.

I also contacted Vadim (crengine author) about margins since I wasn't able to find any hints in crengine source itself but haven't received any answer yet. I'm thinking about adding fixed number to x coordinate so we can merge this PR.

**Comment by tigran123** [comment]
I'll try to reproduce the problem with address space growth.

**Comment by tigran123** [comment]
Ok, I've tested the latest version and it works. I can't reproduce the "infinite growth of AS" issue (must have been cr3cache corruption). My only suggestion is to disable debug printf() for the actual committed version. Btw, margins are a separate issue from links, aren't they? So, why don't we merge this PR now, so that it doesn't get out of sync too far from the master tree?

**Comment by tigran123** [comment]
Actually, another suggestion would be to delete the `Shift-L` command in crereader.lua as it is meaningless there (the links are shown internally by crengine anyway). And also set the show_links_enable = false by default (via new :setDefaults() method).

**Comment by tigran123** [comment]
Oops, following a link on a chm file coredumps:

```
(gdb) bt
#0  0x0000000000668e97 in ldomXPointer::getRect(lvRect&) const ()
Cannot access memory at address 0x100000008
```

Looks like memory corruption.

**Comment by dpavlin** [comment]
I have a mobi tile which also crash, but my backtrace is different:

```
# command to execute: [46]L: page links shortcut keys
## pos=2310

Program received signal SIGSEGV, Segmentation fault.
0x00000000006651cd in ldomXRange::ldomXRange(ldomNode*) ()
(gdb) #0  0x00000000006651cd in ldomXRange::ldomXRange(ldomNode*) ()
#1  0x00000000006bab0d in LVDocView::getCurrentPageLinks(ldomXRangeList&)::LinkKeeper::onElement(ldomXPointerEx*) ()
#2  0x0000000000667847 in ldomXRange::forEach(ldomNodeCallback*) ()
#3  0x00000000006bf269 in LVDocView::getCurrentPageLinks(ldomXRangeList&) ()
#4  0x0000000000638b43 in getPageLinks (L=0x40000378) at cre.cpp:404
#5  0x00000000005124c3 in lj_BC_FUNCC ()
#6  0x00000000005013f0 in lua_pcall ()
#7  0x0000000000408c5e in main (argc=<optimized out>, argv=0x7fffffffe008) at kpdfview.c:76
```

**Comment by dpavlin** [comment]
I will play a bit more with it today, and if I don't manage to crash it on Kindle, I will merge it into master later today

**Comment by tigran123** [comment]
Ok, some of the crashes may not be directly caused by your changes but due to the fact that your changes open access to more of crengine's functionality and therefore to more of its existing bugs.

**Comment by tigran123** [comment]
The previous commit (about getSelections()) seems to have completely broken links --- they don't work anymore.

**Comment by tigran123** [comment]
I forgot to mention, specifically the footnotes in fb2 files no longer work, i.e. I get "No links on this page" message. Before that commit they worked fine, I've tested.

**Comment by tigran123** [comment]
Yes, confirmed, after doing `git revert edd347eb555a97a9b3d2743b1cc6ac36d39f9b5b` and recompiling kpdfview the links work fine again.

**Comment by dpavlin** [comment]
Yes I noticed that after I merged it to master, but #436 fixes that. However, we again have problem with segfault inside crengine.

**Comment by tigran123** [comment]
Well, if the segfault happens with non-fb2 files then it is perfectly understandable. I am sure you know that crengine properly supports only fb2 format --- all the others are, mildly speaking, "experimental" and, more accurately described as "too unstable to be useable". But if it happens with fb2, then it may well be something new or due to our invalid usage or something like that.

I am very surprized that someone is using crengine to read epub files on a Kindle. It is much easier and more comfortable to send the epub to @free.kindle.com address and have it converted to mobi by Amazon. But fb2 they cannot convert so the appropriate option is to use CoolReader3 or our builtin crengine. (one can convert fb2 to mobi via calibre but this is silly because the file size will double, compared to fb2.zip --- so fb2 files should be read on Kindle natively, without conversion)

**Comment by dpavlin** [comment]
I track it down to fix in PR #437

**Comment by dpavlin** [comment]
For rebuild will all changes one needs to apply patch file manually or run `make cleanthirdparty && make fetchthirdparty`

**Pull request merged**
