### PR TITLE
Swipe gesture support

### PR DESCRIPTION
**Pull request by houqp**
also this gesture is used in menu widget for page turn

### CODE REVIEW

**Comment by chrox** [comment]
It works fine on my Paperwhite except the following debug info after each swipe gesture:

```
# {
    ["handler"] = "onInputError",
    ["args"] = {
        [1] = "Waiting for input failed: 22\
"
    }
}
```

**Comment by houqp** [comment]
Ok, I will test it that on my KP the day after tomorrow

**Comment by houqp** [comment]
OK, fix attached, please let me know if the error still exists

**Comment by chrox** [comment]
Good. The problem is solved.

**Pull request merged**
