### PR TITLE
bugfix: remove koptreflow.o in make clean

### PR DESCRIPTION
**Pull request by chrox**
The koptreflow.o was not cleaned when running `make clean` in libk2pdfopt. This patch fix it.

### CODE REVIEW

**Comment by chrox** [comment]
This patch fixed the bug reported in #611.

**Comment by tigran123** [comment]
I think there were two .o files, not just koptreflow.o that were not removed in the clean target.

**Comment by chrox** [comment]
Yes. I add the line `rm -rf *.o` in `make clean`.

**Comment by tigran123** [comment]
Yes, I tested building in emulator mode (after building for ARM) and everything is fine. Thank you.

**Pull request merged**
