### PR TITLE
djvulibre cache size control from Lua script

### PR DESCRIPTION
**Pull request by houqp**

### CODE REVIEW

**Comment by houqp** [comment]
Just notice that @dpavlin has already added this :) Why didn't you assign issue 80 to yourself ;P

close for now.

**Comment by houqp** [comment]
Oh! @dpavlin merged my request ahead of me.... Fine, you have higher APM ;P

**Comment by dpavlin** [comment]
@houqp I wasn't sure that I will get to #80 today :-)

**Comment by houqp** [comment]
LOL, then I should just leave that to you and go back to my crengine branch :P

**Comment by dpavlin** [comment]
We should probably comment it on #32, but it segfaults for me on start. I'm missing fonts, right?

**Comment by houqp** [comment]
@dpavlin  bingo, you need to put font in `./fonts`

**Pull request merged**
