### PR TITLE
font size, line space, font weight, font gamma and viewmode support for crengine

### PR DESCRIPTION
**Pull request by houqp**

### CODE REVIEW

**Comment by houqp** [comment]
@chrox, I am not sure whether my fix for config.lua is correct, it just works for me. Let me know if it's wrong ;p

**Comment by chrox** [comment]
I will test it right now.

**Comment by chrox** [comment]
Line spacing, font size, font weight and gamma are working. But selecting view mode will cause crash as this:

```
lua config error: ./frontend/document/credocument.lua:245: attempt to call method 'setViewMode' (a nil value)
stack traceback:
    ./frontend/document/credocument.lua:245: in function 'setViewMode'
    ./frontend/ui/reader/readerview.lua:173: in function 'handleEvent'
    ./frontend/ui/widget.lua:90: in function 'propagateEvent'
    ./frontend/ui/widget.lua:102: in function 'handleEvent'
    ./frontend/ui/reader/readerconfig.lua:85: in function 'onConfigChoice'
    ./frontend/ui/config.lua:94: in function 'handleEvent'
    ./frontend/ui/widget.lua:90: in function 'propagateEvent'
    ./frontend/ui/widget.lua:102: in function 'handleEvent'
    ./frontend/ui/widget.lua:90: in function 'propagateEvent'
    ./frontend/ui/widget.lua:102: in function 'handleEvent'
    ...
    ./frontend/ui/widget.lua:102: in function 'handleEvent'
    ./frontend/ui/widget.lua:90: in function 'propagateEvent'
    ./frontend/ui/widget.lua:102: in function 'handleEvent'
    ./frontend/ui/widget.lua:90: in function 'propagateEvent'
    ./frontend/ui/widget.lua:102: in function 'handleEvent'
    ./frontend/ui/widget.lua:90: in function 'propagateEvent'
    ./frontend/ui/widget.lua:102: in function 'handleEvent'
    ./frontend/ui/ui.lua:96: in function 'sendEvent'
    ./frontend/ui/ui.lua:207: in function 'run'
    ./reader.lua:113: in main chunk

```

**Comment by houqp** [comment]
That's strange, it works on my PC. Did you updated cre.cpp? The error says it's missing `setViewMode` method, but it's already added to cre.cpp.

**Comment by chrox** [comment]
Yes. After I `make clean && make kpdfview` everything goes right. :)

**Pull request merged**
