### PR TITLE
Bug fix for screen rotate in crereader & fix from @kai777

### PR DESCRIPTION
**Pull request by houqp**
this fixes bug reported by @kai771, i.e. CW rotation
is not handled in crereader.

### CODE REVIEW

**Comment by kai771** [comment]
@houqp btw, you might find my changes to cre.cpp interesting too. They enable you to change view mode without the need to reopen document :).

**Comment by houqp** [comment]
Thanks @kai771 , that's awesome!

**Comment by tigran123** [comment]
Thank you, I will test all this tomorrow.

**Comment by tigran123** [comment]
I wonder if ->setViewMode() is the function we should be using for toggling the view mode, as opposed to ->toggleViewMode(). What I am worried about is the need to update TOC when switching between page/scroll modes --- this sort of bug would be hard to notice by testing (as normally the "pages" of all sections will remain the same when re-typesetting the text in page and scroll modes), so I would have to check the implementations of ->setViewMode() and ->toggleViewMode() to make sure they are equivalent for this purpose.

Update: toggleViewMode() just calls setViewMode() appropriately, so we are okay.

As I promised, I will test everything today.

**Comment by tigran123** [comment]
Everything looks good and user-selection of crereader header font should be in a separate PR.

**Comment by houqp** [comment]
@tigran123 , yeah, i forgot to change create a new branch when adding @kai771 's patch ;p my bad

**Pull request merged**
