### PR TITLE
Tigran djvu contribution

### PR DESCRIPTION
**Pull request by dpavlin**
djvu gamma and render mode improvements, part of issue #217 and subsequent master repository cherry-picking to get correct attribution.

### CODE REVIEW

**Comment by tigran123** [comment]
We are almost there. Only two minor corrections:
1. In djvu.c:drawPage() the variables adjusted_low[] and adjusted_high[] should be "unsigned char" and not "int":
   
   unsigned char adjusted_low[16], adjusted_high[16];
2. In UniReader:toggle_render_mode() there should be a call to self:clearCache() just before the call to self.doc:cleanCache() and also the call to self:redrawCurrentPage() should be AFTER and not BEFORE the call to showInfoMsgWithDelay(...).

**Comment by tigran123** [comment]
Also, perhaps I should add that setting rcountmax=0 is not strictly required for this (djvu contrast support and rendering mode switch), but it is my personal preference as everything works much better (no ghosts from previous pages) when the screen is fully refreshed after each page, not every 5th page. Also, the shortening of "Memory" to "M:" and shortening of "Section" to "Sec" is, imho, a very good idea, but obviously not related to djvu :)

**Comment by dpavlin** [comment]
I'm modifing code here more-or-less blindly, so if I did more mistakes I would welcome pull request :-)

**Comment by tigran123** [comment]
Everything looks fine to me now.

**Comment by tigran123** [comment]
I am reading the FAQ on cloning github repository and creating pull requests. I have never used github before... For this change let's do it the way you have done it (i.e. via your repository), but for the next I will push it to my forked copy (when I managed to create it :) and do it properly, as you suggest (i.e. via "pull requests").

**Comment by tigran123** [comment]
Ok, I have cloned the hwhw repository and will eventually put all my changes to it.

**Comment by dpavlin** [comment]
Thanks for github effort, I'll merge this one and wait for your future pull requests

**Comment by tigran123** [comment]
Hmmm, at the moment crengine does not compile:

[  3%] Building C object crengine/thirdparty/libpng/CMakeFiles/png.dir/pngerror.c.o
In file included from /home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/pngerror.c:17:
/home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/png.h:440:18: error: zlib.h: No such file or directory
In file included from /home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/png.h:444,
                 from /home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/pngerror.c:17:
/home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/pngconf.h:1244: error: expected '=', ',', ';', 'asm' or '**attribute**' before '_' token
/home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/pngconf.h:1245: error: expected '=', ',', ';', 'asm' or '**attribute**' before '_' token
/home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/pngconf.h:1246: error: expected '=', ',', ';', 'asm' or '**attribute**' before '_' token
In file included from /home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/pngerror.c:17:
/home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/png.h:1188: error: expected specifier-qualifier-list before 'z_stream'
/home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/png.h:2975: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'png_zalloc'
/home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/png.h:2978: error: expected ')' before 'png_ptr'
/home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/pngerror.c: In function 'png_format_buffer':
/home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib/crengine/thirdparty/libpng/pngerror.c:150: error: 'png_struct' has no member named 'chunk_name'
make[3]: *_\* [crengine/thirdparty/libpng/CMakeFiles/png.dir/pngerror.c.o] Error 1
make[3]: Leaving directory `/home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib'
make[2]: *** [crengine/thirdparty/libpng/CMakeFiles/png.dir/all] Error 2
make[2]: Leaving directory`/home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib'
make[1]: **\* [all] Error 2
make[1]: Leaving directory `/home/tigran/Kindle/Kindle-PDF-Viewer/tigran123-fork/kindlepdfviewer/kpvcrlib'
make: **\* [kpvcrlib/crengine/crengine/libcrengine.a] Error 2

I will try to understand what has changed that broke the compilation...

**Comment by dpavlin** [comment]
@tigran123 I'm using `make customupdate HOST=arm-kindle-linux-gnueabi` to build Kindle package. Did you issue `make fetchthirdparty` to update all git submodules and dependecies?

**Comment by tigran123** [comment]
Yes, I did "make fetchthirdparty" and then "make thirdparty", just like before. Previously it succeeded. Now it fails. But I see that a lot of "third party" stuff is different, e.g. mupdf/thirdparty/zlib-1.2.7/zlib.h didn't exist --- instead, there was version 1.2.5. Btw, running "make customupdate HOST=arm-kindle-linux-gnueabi" results in more errors:

arm-kindle-linux-gnueabi-gcc -c -O3 --sysroot=/usr/local/arm/arm-kindle-linux-gnueabi/arm-kindle-linux-gnueabi/sysroot/ -march=armv6 -Iluajit-2.0/src -Imupdf/ -Imupdf/thirdparty/freetype-2.4.9/include -Imupdf/fitz ft.c -o ft.o
ft.c:21:22: error: ft2build.h: No such file or directory
ft.c:22:10: error: #include expects "FILENAME" or <FILENAME>
ft.c:30: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'freetypelib'
ft.c:33: error: expected specifier-qualifier-list before 'FT_Face'
ft.c: In function 'newFace':
ft.c:45: error: 'KPVFace' has no member named 'allocated_face'
ft.c:47: error: 'FT_Error' undeclared (first use in this function)
ft.c:47: error: (Each undeclared identifier is reported only once
ft.c:47: error: for each function it appears in.)
ft.c:47: error: expected ';' before 'error'

However, the file ft.c has not changed. Ah, I see. It refers via -I to freetype-2.4.9 but we are now using 2.4.10. Very strange that nobody noticed this. I will try to fix it now (i.e. change in the Makefile 2.4.9 -> 2.4.10). Let's see if it fixes all the problems :)

**Comment by tigran123** [comment]
The compilation of ft.c now (with the change to Makefile) succeeds, but kpvcrlib/crengine/thirdparty/libpng/pngerror.c still fails because it doesn't find zlib.h. There are 6 zlib.h files in the tree:
$ find -name zlib.h
./kpvcrlib/crengine/thirdparty/freetype/src/gzip/zlib.h
./kpvcrlib/crengine/thirdparty/zlib/zlib.h
./mupdf/thirdparty/openjpeg-1.5.0-patched/thirdparty/libz/zlib.h
./mupdf/thirdparty/openjpeg-1.5.0-patched/thirdparty/include/zlib.h
./mupdf/thirdparty/zlib-1.2.7/zlib.h
./mupdf/thirdparty/freetype-2.4.10/src/gzip/zlib.h

I assume that crengine is supposed to use one of the first two. But what prevents it from finding it? It doesn't use normal standard Makefiles but this exotic "cmake" thingy, so it is not obvious (to me) what is wrong...

**Comment by tigran123** [comment]
Ok, I see the error is in kpvcrlib/CMakeLists.txt --- it refers to zlib-1.2.5 but the actual zlib that comes with mupdf is now 1.2.7.

**Comment by dpavlin** [comment]
On Mon, Aug 27, 2012 at 05:26:22AM -0700, Tigran Aivazian wrote:

> Ok, I see the error is in kpvcrlib/CMakeLists.txt --- it refers to zlib-1.2.5 but the actual zlib that comes with mupdf is now 1.2.7.

Oh, this probably means that mupdf-thirdparty.zip upgraded zlib and our
build scripts are still depending on old version. Good catch.

## 

Dobrica Pavlinusic               2share!2flame            dpavlin@rot13.org
Unix addict. Internet consultant.             http://www.rot13.org/~dpavlin

**Comment by tigran123** [comment]
I am having trouble specifying which of my commits to include in the pull requests. By default it includes all of my commits, but I only want to send two (the Makefile change and djvu enhancements). How do I narrow down which commits to include in a pull request? There seems to be no button or option to select anywhere....

**Comment by dpavlin** [comment]
That's my fault. I merged initial version of the patch and now master is in flux. Let me fix that by cherry picking your commits, but it seems I will have to drop modifications to build process because it broke compilation under emulation. I have only

`
export PATH=/home/dpavlin/t61p/k3libre/x-tools-glib2.5/arm-kindle-linux-gnueabi/bin/:$PATH
make customupdate HOST=arm-kindle-linux-gnueabi
`
and it does compile arm binary for me. Can we somehow solve sysroot issue in another way?

we should probably open seprate issue for this instead of talking on this one which is closed :-)

**Comment by tigran123** [comment]
Yes, those changes were not intended to be merged anywhere, i.e. they were "private to my build environment". Perhaps I should not have pushed them to my remote tree on github. Sorry, this is my first experience with github, so I make these silly mistakes.

Btw, I got an email from Jeremy McAnally who says that I cannot pick which commits go into a pull request.

**Comment by dpavlin** [comment]
In this case, I merged you branch and then revert(ed) last commit.

When you have branch for which you issued pull request you really can't change specification, but it's possible to create new branch from upstream (origin) master `using git checkout -b new-branch-name origin/master` and then use `git cherrypick sha-hash-of-commit` one by one to apply just some changes and submit pull request for this branch.

**Pull request merged**
