### PR TITLE
k4 framebuffer support rewrite & screen saver, usb plugin support

### PR DESCRIPTION
**Pull request by houqp**
- previous implementation make fb.bb has double pitch
  compared to other blitbuffer, which leads to segfault
  on blitFullFrom method.
- I also gave it a try to implement partial refresh and repaint-area calculation. Hope I did not mess up the code, if I did, please let me know :)

### CODE REVIEW

**Comment by dpavlin** [comment]
@houqp I'm not ignoring this patch, I just don't have k4 to test on :-)

**Comment by houqp** [comment]
@dpavlin It's OK :) 

But aside from the framebuffer part, other hacks should also work in K3. Also I don't have a K3 now, so if you have time, please help test the framebuffer in K3 ;P Hope I did not break anything in K3.

**Comment by hwhw** [comment]
Sorry, been veeery distracted over the last days. Too much other work. But not forgotten about kpdfview...

**Comment by houqp** [comment]
me too :) 

I think I have finished all the K4 related code so far. If you guys find anything that I missed, please tell me, because I will have to return the K4 to my friend in this week ;P

**Pull request merged**
