### PR TITLE
Modify those functions about the view_mode equal "page" when the kindle in Horizontal screen state.

### PR DESCRIPTION
**Pull request by ZenRoi**
Modify those functions about the view_mode equal "page" when the kindle in Horizontal screen state.

### CODE REVIEW

**Comment by tigran123** [comment]
With this change the TOC doesn't work, i.e. following a TOC entry jumps to a completely wrong location. Also, changing the font and the header font causes the location to always jump to the end of the book (maybe this is a "random location", but it just happened to be the end of the book in the couple of tests I have done). I tested with a random/typical fb2 book, nothing special about it.

**Comment by houqp** [comment]
I tested it only on EPUBs and cannot reproduce the bugs you mentioned. Could you provide one of the fb2 book for testing purpose? I don't have any fb2 books here ;p

**Comment by tigran123** [comment]
I forgot to mention that to reproduce the bug you have to change either the base font or the header font. And if you close the document and re-open it again then it will work UNTIL you change the base or header font again.

**Comment by tigran123** [comment]
Yes, sure, here is a test fb2 file:

http://www.bibles.org.uk/test.fb2.zip

**Comment by houqp** [comment]
Thanks for the test file, bug confirmed :)

And this is caused by out of date `self.toc` after document is reformatted. That means every time we re-typeset the document with new font, new line space or what ever, we need to set `sel.toc` to nil so new toc can be retrieved on request.

I will leave the fix to @ZenRoi , since it's a good chance for him to practice on git.

**Comment by tigran123** [comment]
Ah, I see, yes, that makes sense. Thank you for the explanation :)

**Pull request merged**
