### PR TITLE
bugfix: fixed missing words in last line

### PR DESCRIPTION
**Pull request by chrox**
This patch fixed the "text cut off at page bottom" bug reported by @tigran123 at #546.

### CODE REVIEW

**Comment by chrox** [comment]
@tigran123  Thanks to Willus, the author of K2pdfopt. He told me that I need only one line to fix the bug. And it truns out that he is right. That line just works like a charm. To test this patch, you need to rebuild libk2pdfopt.

**Comment by tigran123** [comment]
It doesn't actually compile at the moment:

```
In file included from k2pdfoptlib/k2pdfopt.h:44:0,
                 from koptreflow.h:26,
                 from koptreflow.c:30:
willuslib/willus.h:303:8: error: conflicting types for 'dprintf'
/home/usrlocal/arm-2012.03/bin/../arm-none-linux-gnueabi/libc/usr/include/stdio.h:421:12: note: previous declaration of 'dprintf' was here
make[1]: *** [koptreflow.o] Error 1
make[1]: Leaving directory `/home/tigran/Kindle/kindlepdfviewer/libk2pdfopt'
make: *** [libs/libk2pdfopt.so.1] Error 2
```

**Comment by tigran123** [comment]
Hmmm, this suggests that you are using a different toolchain version. We are using 2012.03 from CS.

**Comment by chrox** [comment]
This bug is already fixed in PR #603. I simply removed the dprintf definition in libk2pdfopt as it's never used.

**Comment by chrox** [comment]
I use the same toolchain as you guys do. But probably I've commented out the dprintf in stdio before. I'm sorry for the inconvenience.

**Comment by tigran123** [comment]
No problem, thank you for fixing it so quickly.

**Pull request merged**
