### PR TITLE
fix getCurrentPageLinks segfault on links without target

### PR DESCRIPTION
**Pull request by dpavlin**
It's also reported to upstream at:

https://sourceforge.net/tracker/?func=detail&aid=3577117&group_id=191284&atid=936756

### CODE REVIEW

**Comment by houqp** [comment]
nice catch :) Seems that Vadim has stopped working on coolreader for a long time. Did he reply your mail?

**Comment by tigran123** [comment]
What I didn't understand is whether this fix will be automatically picked up if we do "make fetchthirdparty"? If yes, then applying the patch would fail, right?

**Comment by tigran123** [comment]
Ah, I understand now, ignore my question :)

**Comment by tigran123** [comment]
@dpavlin nice catch indeed, well done!

**Comment by dpavlin** [comment]
@houqp no, Vadmin didn't reply but there are recent commits at http://crengine.git.sourceforge.net/git/gitweb.cgi?p=crengine/crengine;a=summary so I'm still hopeful :-)

**Pull request merged**
