### PR TITLE
some minor tweaks before introducing gesture detection module

### PR DESCRIPTION
**Pull request by houqp**
- refine single tap touch input simulation in input.c
- update document.lua according to API change in cre.cpp
- add time subtable to lua inputevent table
- add back waitForInput timeout for emulator

### CODE REVIEW

**Comment by chrox** [comment]
@houqp I would like to get a Kindle Touch to test the new UI since Kindle Paperwhite is so hard to get in China. BTW, is the basic functionality of the new UI usable in Kindle Touch?

**Comment by houqp** [comment]
No, it's not usable yet because zoom mode is not implemented. So it is only usable for book supported by CREngine. You can indeed test it first in emulator to see how simple it is now ;p

PW is out of stock in US too, crazy amazon.

**Comment by chrox** [comment]
Thanks. Anyway I will get involved in the new UI development as soon as I get my KT.

**Comment by houqp** [comment]
That will be awesome :) Let me know if you need to buy PW, I can send you one, but it will need sometime before I can get it from Amazon ;p

**Comment by chrox** [comment]
Thanks. I have got one from taobao. Now the KP is already jailbroken and usbnetworked. And I will compile the new UI code for it now. :)

**Comment by houqp** [comment]
merging for now since no objections ;p

**Comment by houqp** [comment]
WOW, remember to keep airplane mode on ;p

**Pull request merged**
