### PR TITLE
bugfix: set toc/bookmark window dimension smaller than screen size to fix Toc crash in #815

### PR DESCRIPTION
**Pull request by chrox**

### CODE REVIEW

**Comment by houqp** [comment]
good catch. Though I don't really understand why ;p

But I guess you need to send it to new repo now :)

**Comment by chrox** [comment]
Since the nightly build script hasn't supported koreader yet we probably
need to fix it in the new_ui_code branch. And then cherry-pick this patch
into koreader repo.

**Comment by hwhw** [comment]
Agreed. But we probably need to get rid of the new_ui_code branch as fast as possible. However - it's clear that the build workflow must be working and the nightly builds set up, yes.

**Comment by houqp** [comment]
Oh, yeah, you are right :)

**Pull request merged**
