### PR TITLE
Screen offset fixes

### LINKED ISSUE #351: hotkeys for pdf links are 'out of focus' in some modes
take https://github.com/downloads/tigran123/russian-synodal-bible/Russian-Synodal-Bible-USletter-twocolumn.pdf
change to 'Shift +A'
Press 'L'
Observe that hotkeys are not at proper positions

I am almost sure this was not an issue after the first implementation of the feature.

P.S.: Release 2012.09

### PR DESCRIPTION
**Pull request by dpavlin**
This pull request tries to correctly setup screen offsets to fix #351

### CODE REVIEW

**Comment by tigran123** [comment]
I'll test it now.

**Comment by tigran123** [comment]
No, still broken, but differently. Try the russian Bible A4 file and press Shift-A on the TOC page. You will see how the second column's shortcuts are to the left of the underlines and there is also some mess at the bottom of the first column of shortcuts.

**Comment by tigran123** [comment]
Actually, in single-column TOC it is also broken still, e.g. on this one:

http://urantia-book.org/downloads/English-UK/Urantia-ENG-UK-A4-twocolumn.zip

If you press Shift-A and then L you will see the links shifted to the right of where they should be.

**Comment by dpavlin** [comment]
First commit was obviously wrong because lua local variables are passed by reference, and then I got distracted by various other bugs I stumbled upon when testing it.

Having said all that, I think we should really move to new_ui branch to provide some encapsulation instead of this gross hack.

**Comment by dpavlin** [comment]
If this works, I will cherry-pick and rebase this patch to have just one change for offset restore.

**Comment by tigran123** [comment]
Ok, I will test it for you now (though I am in the middle of sorting out certain mess, which I really ought to finish before switching to anything else... :)

**Comment by tigran123** [comment]
Hmmm, very curious --- now we get a coredump ("Segmentation fault") if we go to `Shift-S` and then page down `Next` so that there are only three links still visible at the bottom of the page and then press `L`. Here is the stacktrace:

```
*** glibc detected *** ./kpdfview.emulator-dpavlin: free(): invalid size: 0x00000000012be490 ***
======= Backtrace: =========
/lib64/libc.so.6[0x341167bfee]
/lib64/libX11.so.6(_XUnregisterFilter+0x47)[0x341523c1e7]
/lib64/libSDL-1.2.so.0[0x341ce4139b]
/lib64/libSDL-1.2.so.0(SDL_VideoQuit+0x4e)[0x341ce309ce]
/lib64/libSDL-1.2.so.0(SDL_QuitSubSystem+0x45)[0x341ce08345]
/lib64/libSDL-1.2.so.0(SDL_Quit+0xe)[0x341ce083fe]
/lib64/libSDL-1.2.so.0[0x341ce08a4f]
/lib64/libpthread.so.0[0x3411a0efe0]
./kpdfview.emulator-dpavlin[0x407edd]
./kpdfview.emulator-dpavlin[0x510403]
./kpdfview.emulator-dpavlin[0x4ff330]
./kpdfview.emulator-dpavlin[0x40765e]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x3411621735]
./kpdfview.emulator-dpavlin[0x407add]
======= Memory map: ========
00400000-0096c000 r-xp 00000000 08:05 51912688                           /home/tigran/Kindle/kindlepdfviewer/kpdfview.emulator-dpavlin
00b6b000-00b8a000 rw-p 0056b000 08:05 51912688                           /home/tigran/Kindle/kindlepdfviewer/kpdfview.emulator-dpavlin
00b8a000-00be6000 rw-p 00000000 00:00 0 
0128d000-01963000 rw-p 00000000 00:00 0                                  [heap]
3e8f0000-3e900000 r-xp 00000000 00:00 0 
40208000-40228000 rw-p 00000000 00:00 0 
40b6d000-40b8d000 rw-p 00000000 00:00 0 
40dd0000-40df0000 rw-p 00000000 00:00 0 
4115d000-4117d000 rw-p 00000000 00:00 0 
4127b000-4129b000 rw-p 00000000 00:00 0 
415b6000-415d6000 rw-p 00000000 00:00 0 
416c0000-416e0000 rw-p 00000000 00:00 0 
3411200000-3411220000 r-xp 00000000 08:03 154771                         /usr/lib64/ld-2.15.so
341141f000-3411420000 r--p 0001f000 08:03 154771                         /usr/lib64/ld-2.15.so
3411420000-3411421000 rw-p 00020000 08:03 154771                         /usr/lib64/ld-2.15.so
3411421000-3411422000 rw-p 00000000 00:00 0 
3411600000-34117ac000 r-xp 00000000 08:03 174786                         /usr/lib64/libc-2.15.so
34117ac000-34119ac000 ---p 001ac000 08:03 174786                         /usr/lib64/libc-2.15.so
34119ac000-34119b0000 r--p 001ac000 08:03 174786                         /usr/lib64/libc-2.15.so
34119b0000-34119b2000 rw-p 001b0000 08:03 174786                         /usr/lib64/libc-2.15.so
34119b2000-34119b7000 rw-p 00000000 00:00 0 
3411a00000-3411a16000 r-xp 00000000 08:03 180478                         /usr/lib64/libpthread-2.15.so
3411a16000-3411c16000 ---p 00016000 08:03 180478                         /usr/lib64/libpthread-2.15.so
3411c16000-3411c17000 r--p 00016000 08:03 180478                         /usr/lib64/libpthread-2.15.so
3411c17000-3411c18000 rw-p 00017000 08:03 180478                         /usr/lib64/libpthread-2.15.so
3411c18000-3411c1c000 rw-p 00000000 00:00 0 
3411e00000-3411e03000 r-xp 00000000 08:03 154799                         /usr/lib64/libdl-2.15.so
3411e03000-3412002000 ---p 00003000 08:03 154799                         /usr/lib64/libdl-2.15.so
3412002000-3412003000 r--p 00002000 08:03 154799                         /usr/lib64/libdl-2.15.so
3412003000-3412004000 rw-p 00003000 08:03 154799                         /usr/lib64/libdl-2.15.so
3412600000-34126fa000 r-xp 00000000 08:03 180482                         /usr/lib64/libm-2.15.so
34126fa000-34128f9000 ---p 000fa000 08:03 180482                         /usr/lib64/libm-2.15.so
34128f9000-34128fa000 r--p 000f9000 08:03 180482                         /usr/lib64/libm-2.15.so
34128fa000-34128fb000 rw-p 000fa000 08:03 180482                         /usr/lib64/libm-2.15.so
3414e00000-3414e15000 r-xp 00000000 08:03 180483                         /usr/lib64/libgcc_s-4.7.2-20120921.so.1
3414e15000-3415014000 ---p 00015000 08:03 180483                         /usr/lib64/libgcc_s-4.7.2-20120921.so.1
3415014000-3415015000 rw-p 00014000 08:03 180483                         /usr/lib64/libgcc_s-4.7.2-20120921.so.1
3415200000-3415334000 r-xp 00000000 08:03 180496                         /usr/lib64/libX11.so.6.3.0
3415334000-3415534000 ---p 00134000 08:03 180496                         /usr/lib64/libX11.so.6.3.0
3415534000-3415535000 r--p 00134000 08:03 180496                         /usr/lib64/libX11.so.6.3.0
3415535000-341553a000 rw-p 00135000 08:03 180496                         /usr/lib64/libX11.so.6.3.0
3415600000-341561d000 r-xp 00000000 08:03 180495                         /usr/lib64/libxcb.so.1.1.0
341561d000-341581c000 ---p 0001d000 08:03 180495                         /usr/lib64/libxcb.so.1.1.0
341581c000-341581d000 r--p 0001c000 08:03 180495                         /usr/lib64/libxcb.so.1.1.0
341581d000-341581e000 rw-p 0001d000 08:03 180495                         /usr/lib64/libxcb.so.1.1.0
3415a00000-3415a02000 r-xp 00000000 08:03 180494                         /usr/lib64/libXau.so.6.0.0
3415a02000-3415c02000 ---p 00002000 08:03 180494                         /usr/lib64/libXau.so.6.0.0
3415c02000-3415c03000 r--p 00002000 08:03 180494                         /usr/lib64/libXau.so.6.0.0
3415c03000-3415c04000 rw-p 00003000 08:03 180494                         /usr/lib64/libXau.so.6.0.0
3415e00000-3415e10000 r-xp 00000000 08:03 180508                         /usr/lib64/libXext.so.6.4.0
3415e10000-3416010000 ---p 00010000 08:03 180508                         /usr/lib64/libXext.so.6.4.0
3416010000-3416011000 r--p 00010000 08:03 180508                         /usr/lib64/libXext.so.6.4.0
3416011000-3416012000 rw-p 00011000 08:03 180508                         /usr/lib64/libXext.so.6.4.0
3416200000-3416209000 r-xp 00000000 08:03 180497                         /usr/lib64/libXrender.so.1.3.0
3416209000-3416408000 ---p 00009000 08:03 180497                         /usr/lib64/libXrender.so.1.3.0
3416408000-3416409000 r--p 00008000 08:03 180497                         /usr/lib64/libXrender.so.1.3.0
3416409000-341640a000 rw-p 00009000 08:03 180497                         /usr/lib64/libXrender.so.1.3.0
3417a00000-3417a07000 r-xp 00000000 08:03 180511                         /usr/lib64/libXrandr.so.2.2.0
3417a07000-3417c06000 ---p 00007000 08:03 180511                         /usr/lib64/libXrandr.so.2.2.0
3417c06000-3417c07000 r--p 00006000 08:03 180511                         /usr/lib64/libXrandr.so.2.2.0
3417c07000-3417c08000 rw-p 00007000 08:03 180511                         /usr/lib64/libXrandr.so.2.2.0
3418a00000-3418a05000 r-xp 00000000 08:03 180512                         /usr/lib64/libXfixes.so.3.1.0
3418a05000-3418c04000 ---p 00005000 08:03 180512                         /usr/lib64/libXfixes.so.3.1.0
3418c04000-3418c05000 r--p 00004000 08:03 180512                         /usr/lib64/libXfixes.so.3.1.0
3418c05000-3418c06000 rw-p 00005000 08:03 180512                         /usr/lib64/libXfixes.so.3.1.0
3419600000-34196e5000 r-xp 00000000 08:03 180484                         /usr/lib64/libstdc++.so.6.0.17
34196e5000-34198e4000 ---p 000e5000 08:03 180484                         /usr/lib64/libstdc++.so.6.0.17
34198e4000-34198ec000 r--p 000e4000 08:03 180484                         /usr/lib64/libstdc++.so.6.0.17
34198ec000-34198ee000 rw-p 000ec000 08:03 180484                         /usr/lib64/libstdc++.so.6.0.17
34198ee000-3419903000 rw-p 00000000 00:00 0 
3419a00000-3419a09000 r-xp 00000000 08:03 180513                         /usr/lib64/libXcursor.so.1.0.2
3419a09000-3419c09000 ---p 00009000 08:03 180513                         /usr/lib64/libXcursor.so.1.0.2
3419c09000-3419c0a000 r--p 00009000 08:03 180513                         /usr/lib64/libXcursor.so.1.0.2
3419c0a000-3419c0b000 rw-p 0000a000 08:03 180513                         /usr/lib64/libXcursor.so.1.0.2
341ce00000-341ce6b000 r-xp 00000000 08:03 138386                         /usr/lib64/libSDL-1.2.so.0.11.3
341ce6b000-341d06b000 ---p 0006b000 08:03 138386                         /usr/lib64/libSDL-1.2.so.0.11.3
341d06b000-341d06c000 r--p 0006b000 08:03 138386                         /usr/lib64/libSDL-1.2.so.0.11.3
341d06c000-341d06d000 rw-p 0006c000 08:03 138386                         /usr/lib64/libSDL-1.2.so.0.11.3
341d06d000-341d09d000 rw-p 00000000 00:00 0 
7f1837f07000-7f1837f09000 rw-p 00000000 00:00 0 
7f1837f09000-7f18380de000 rw-s 00000000 00:04 655366                     /SYSV00000000 (deleted)
7f18380de000-7f1838152000 rw-p 00000000 00:00 0 
7f1838234000-7f183e661000 r--p 00000000 08:03 174659                     /usr/lib/locale/locale-archive
7f183e661000-7f183e667000 rw-p 00000000 00:00 0 
7f183e679000-7f183e681000 rw-p 00000000 00:00 0 
7fffa00fa000-7fffa011b000 rw-p 00000000 00:00 0                          [stack]
7fffa01ff000-7fffa0200000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted
```

On the second execution I got `Aborted` and the full stacktrace/memory map as above. On the first run I just got "Segmentation fault". I can recompile the whole withing with "-g" and then run gdb kpdfview core if you wish?

**Comment by tigran123** [comment]
Btw, we get the same coredump in the master branch without your changes (of this PR). But in the master branch if we do `Shift-S` and then page `Next` there are no visible links at the bottom of the page, i.e. the view is positioned differently.

Also, when the links are visible (i.e. in dpavlin/screen_offset branch), they are greyed out i.e. they properly belong to the previous view. So, maybe this is a separate bug "crash when pressing 'L' with links not in the current view".

Also, the actual bug you are fixing now seems to be fixed, i.e. `L` does position shortcuts correctly (when it doesn't crash)

**Comment by tigran123** [comment]
Wait, something very strange is going on here. I'll re-compile and re-test everything and will get back to you asap.

**Comment by tigran123** [comment]
Ok, the "strange things" were caused by using history/\* files created by dpavlin/screen_offset branch when running master branch, so ignore that.

Now, I have recompiled and retested from scratch. I found the following bug in the current state of screen_offset branch: if you press `Shift-S` and then `L` and then `Back` the page is shifted to the bottom of the screen. I would expect it to stay where it was before pressing `Back`.

Also, I confirm that the coredump bug is present in the master branch also, so it should be investigated separately. It always coredumps if you press `L` when the links are either not visible in the current view or greyed out.

**Comment by tigran123** [comment]
Update on the coredump issue: I tracked it down to the call to `SDL_WaitEvent(&event)` in the function `input.c:SDL_WaitEvent(&event)`. I.e. I see the output from a debug fprintf() just before it but not immediately after it.

**Comment by tigran123** [comment]
Update on the coredump issue: it is not specific to SDL (emulator), i.e. it coredumps in exactly the same way on Kindle 3 as well. I'll try to compile with "-g" the ARM binary as well, and enable coredumps (`ulimit -c unlimited`) and see if I can analyze the ARM coredump to see the corresponding place where it happens.

So, we are definitely doing something wrong with key handling as this is not just an SDL-specific quirk.

**Comment by dpavlin** [comment]
I got stacktrace from gdb which points to `dimRect` which didn't have negative checking until now. With 466be71  fix it doesn't segfaul for me any longer, but it doesn't show any shortcuts on screen until you press fiveway down.

This somehow makes sense because code tries to enumerate links from top of the page and that part is not visible. I'll need to look at code a bit more to figure out how to fix this.

**Comment by tigran123** [comment]
Update on the coredump: -O0 -g compiled kpdfview won't even startup on Kindle, it coredumps straightaway like this:

```
(gdb) bt
#0  0x0015007c in lj_BC_RET () at lj_vm.s:886
#1  0x00130e74 in lua_pcall (L=0x402a91c0, nargs=0, nresults=-1, errfunc=0) at lj_api.c:1034
#2  0x0000e924 in main (argc=3, argv=0xbeb30e14) at kpdfview.c:74
```

(I had to point `set sysroot` to /usr/local/arm/2012.03 for arm-*-gdb to work)

**Comment by tigran123** [comment]
Ok, I'll test your `dimRect` fix now.

**Comment by tigran123** [comment]
Yes, I confirm that with `dimRect` fix it no longer coredumps. But still every press of `Back` in the links mode (`L`) shifts the view a bit --- it shouldn't shift it.

And yes you are right, the shortcuts for the visible links are not visible because they are enumerated from the top of the page and NOT from the top of the current view. If you can fix it without affecting performance of the non-link mode (i.e. normal page view, not after pressing `L`) then please do.

**Comment by tigran123** [comment]
But I wonder why my stracktrace was pointing to a completely different function... Hmmm... maybe `gcc -m32` in the Makefile was confusing all debuginfo? I'll check.

**Comment by tigran123** [comment]
Yes, `gcc -m32` definitely makes a difference, because switching it to `gcc -m64` produces a completely different stracktrace pointing to `ft.c:renderGlyph()`:

```
(gdb) bt
#0  0x000000341167bafc in _int_free () from /lib64/libc.so.6
#1  0x000000341ce2b676 in SDL_FreeCursor () from /lib64/libSDL-1.2.so.0
#2  0x000000341ce2b93a in ?? () from /lib64/libSDL-1.2.so.0
#3  0x000000341ce309b7 in SDL_VideoQuit () from /lib64/libSDL-1.2.so.0
#4  0x000000341ce08345 in SDL_QuitSubSystem () from /lib64/libSDL-1.2.so.0
#5  0x000000341ce083fe in SDL_Quit () from /lib64/libSDL-1.2.so.0
#6  0x000000341ce08a4f in ?? () from /lib64/libSDL-1.2.so.0
#7  <signal handler called>
#8  0x0000000000000000 in ?? ()
#9  0x00000000004a9476 in tt_loader_init (load_flags=4, glyph=<optimized out>, size=0x2937c90, loader=0x7fffed2814e0, glyf_table_only=<optimized out>)
    at thirdparty/freetype-2.4.10/src/truetype/ttgload.c:1918
#10 TT_Load_Glyph (size=0x2937c90, glyph=<optimized out>, glyph_index=49, load_flags=<optimized out>) at thirdparty/freetype-2.4.10/src/truetype/ttgload.c:2027
#11 0x0000000000481da8 in FT_Load_Glyph (load_flags=4, glyph_index=<optimized out>, face=0x28d6ac0) at thirdparty/freetype-2.4.10/src/base/ftobjs.c:694
#12 FT_Load_Glyph (face=0x28d6ac0, glyph_index=49, load_flags=<optimized out>) at thirdparty/freetype-2.4.10/src/base/ftobjs.c:563
#13 0x000000000040d519 in renderGlyph (L=0x40665378) at ft.c:70
#14 0x0000000000512e13 in lj_BC_FUNCC ()
#15 0x0000000000501d40 in lua_pcall ()
#16 0x0000000000407c12 in main (argc=3, argv=0x7fffed2818b8) at kpdfview.c:74
```

**Comment by NiLuJe** [comment]
@tigran123 : Good point. I'm not familiar with LUA/luajit at all, but maybe it shouldn't be forced to 32bits in EMU mode (if it supports x86_64 properly)?

**Comment by tigran123** [comment]
@NiLuje Yes, looks like I can't get accurate stacktraces when building on x86_64 :(
Any help you can render would be appreciated (otherwise I'll have to install FC17 32 bit in a VirtualBox and have 5-6 times slower compiles...)

**Comment by tigran123** [comment]
My current compiles (of the whole thing including customupdate) take less than 2 minutes, so switching to 10 minute compiles would be a nightmare...

**Comment by NiLuJe** [comment]
@tigran123 : It's trivial enough to do, but I'll push something later tonight to 'fix' this. And update the default recommended debug CFLAGS: try adding -fno-omit-frame-pointer, that might lead to more accurate stacktraces (it was enabled by default somewhat recently, in GCC 4.6 or 4.7 IIRC).

**Comment by tigran123** [comment]
@NiLuJe Oh, I was going to suggest that it is ok to use FC17/23bit in a vbox, because it is never 100% reliable to run 32-bit apps in a 64-bit environment anyway.

When you say "trivial enough to do" you mean that you have figured out why my ARM binary compiled on x86_64  (with -O0 -g) coredumps as well? Without this, it would still make sense to only trust compilation on a 32bit platform. But if you have figured out this as well, then great --- I look forward to your fixes and will greatly thank you for removing the need to work in VirtualBox! :)

**Comment by tigran123** [comment]
@dpavlin Yes, I confirm that with the latest patch we can now see the shortcuts for visible links.

However, `Back` from `L` still changes the current view.

**Comment by tigran123** [comment]
@NiLuJe The safest thing is if we could get hold of "2012.03" TC compiled and tested to run natively on x86_64. I emailed the engineer from MG asking about it.

**Comment by tigran123** [comment]
Recompiling with `-fno-omit-frame-pointer` (and keeping `-m32`) produces yet another (still wrong) backtrace:

```
(gdb) bt
#0  0x000000341167bafc in _int_free () from /lib64/libc.so.6
#1  0x000000341ce2b676 in SDL_FreeCursor () from /lib64/libSDL-1.2.so.0
#2  0x000000341ce2b93a in ?? () from /lib64/libSDL-1.2.so.0
#3  0x000000341ce309b7 in SDL_VideoQuit () from /lib64/libSDL-1.2.so.0
#4  0x000000341ce08345 in SDL_QuitSubSystem () from /lib64/libSDL-1.2.so.0
#5  0x000000341ce083fe in SDL_Quit () from /lib64/libSDL-1.2.so.0
#6  0x000000341ce08a4f in ?? () from /lib64/libSDL-1.2.so.0
#7  <signal handler called>
#8  0x0000000000480335 in FT_Get_Char_Index (face=<optimized out>, charcode=0) at thirdparty/freetype-2.4.10/src/base/ftobjs.c:3306
#9  0x000000000040d8a8 in getKerning (L=0x40ef1378) at ft.c:130
#10 0x0000000000512e43 in lj_BC_FUNCC ()
#11 0x0000000000501d70 in lua_pcall ()
#12 0x0000000000407c42 in main (argc=3, argv=0x7fff860592e8) at kpdfview.c:74
```

**Comment by dpavlin** [comment]
a696a4d was surposed to be fix for `Back` and `L` and I can reproduce it with `Shift+S` on bottom half of TOC in `Russian-Synodal-Bible-USletter-twocolumn.pdf` but not on `urantia-eng-uk-A4-twocolumn.pdf` strage...

**Comment by tigran123** [comment]
Hmm, but I reproduced it with _both_ Russian Bible and Urantia-A4. Strange, I'll start from scratch (clean git clone, feththirdparty etc etc) and re-test everything to be sure.

**Comment by tigran123** [comment]
Also, I am installing FC17 32bit in VirtualBox and will test there as well (but if @NiLuJe does make a miracle and solve the mysterious coredumps then I'll be only too happy to forget the vbox environment until we hit the next 32/64bit incompatibility issue :)

**Comment by tigran123** [comment]
Ok, retested everything and I reproduce the bug (`Back` from `L` shifts the view) on the `Russian-Synodal-Bible-USletter-twocolumn.pdf` but NOT (i.e. it works fine on it) on `Urantia-ENG-UK-A4-twocolumn.pdf`. Indeed, very strange.

So, I repeat, on Russian Bible pressing `Back` after `Shift-S` and `L` and `Next` shifts the view up. But on Urantia-A4 it stays where it was.

**Comment by tigran123** [comment]
Please note the difference (it may be essential) between Russian Bible and Urantia-A4. The Bible has no visible (i.e. ungreyed) links at the bottom after `Shift-S` + `Next`, but Urantia-A4 has quite a few of them visible.

**Comment by tigran123** [comment]
Actually, strictly speaking counting that last link (pointing to "1-е Коринфянам", page 767) as visible is a bug, i.e. it is greyed out and should be considered invisible, i.e. no shortcut attached to it. Otherwise, why do you consider the other two more visible (to pages 759 and 807)? They are just as greyed out as the third one, so should be handled in the same way --- either attach shortcut to all three or to none.

**Comment by tigran123** [comment]
Ok, on FC17 32bit stacktrace is accurate (even without -g and -fno-omit-frame-pointer), look:

```
(gdb) bt
#0  0x080507a2 in dimRect (L=0xb73131c0) at blitbuffer.c:491
#1  0x08159297 in lj_BC_FUNCC ()
#2  0x0814885d in lua_pcall ()
#3  0x0804dc61 in main (argc=3, argv=0xbfee0914) at kpdfview.c:74
```

(and bidirection clipboard works too, the above comes straight from VirtualBox). Also, I overestimated the badness of emulation --- the whole compile completed in "mere" 3 minutes 51 seconds, i.e. about twice as slow as on the real hardware, so it is tolerable. I will also test if I can get the correct stracktrace when compiling the ARM binary --- if I can, then I will stay "in the box", unless @NiLuJe does something extraordinary and makes all of the above irrelevant with some "magic trick" :)

**Comment by tigran123** [comment]
Actually, the video refresh is so excruciatingly slow in Virtual Box (even with "Guest Additions" installed) that serious work in it is impossible... So, for now I'll work on the real hardware but for actual builds (to go into Downloads section) I'll use FC17 32 bit.

**Comment by NiLuJe** [comment]
@tigran123 : The fact that you're running a x86-ARM cross TC on x86_64 should produce strictly the same stuff as if you were using an x86_64-ARM TC (or anything-ARM, really), so, no need to worry on the native front. As long as it runs successfully on your box (multilib x86 properly setup), it will produce the exact same code as if it were run on x86 ;).

The issue seems to be solely on the EMU side of things... I don't know how the JIT stuff is implemented, but it may introduce some weird stuff that throws GDB off on some archs, which may explain the different traces on x86 vs. x86_64...

That still leaves the question of why the official docs recommend to build the native part of things in 32bits for luajit... (That comes from upstream's comments in the Makefile, and their docs).

**Comment by NiLuJe** [comment]
Huh. I was confused. We already build luajit for the native arch in EMU mode. >_<"

So, err, @tigran123: where were you switching m32/m64? Or am I confused, and are all of those stacktraces from an ARM binary, not an EMU one?

**Comment by tigran123** [comment]
@NiLuJe No, no, the issue is NOT solely on the EMU side of things --- as I said, my ARM binary produced on x86_64 crashes on Kindle IF compiled with "-O0 -g" and otherwise (i.e. with our standard CFLAGS) produces the false stacktrace (even if I add -fno-omit-frame-pointer). This is why I said that for "official" builds (ARM of course) to go into Downloads section I'll use FC17 32bit to build them.

**Comment by NiLuJe** [comment]
@tigran123 : Okay, so I got everything wrong ;D. Those were stacktraces from an ARM binary, then? (I'm seeing SDL calls in some of them, so I'm confused).

**Comment by tigran123** [comment]
No, those were stacktraces from x86_64 binary (the wrong ones). Let's summarize:
1. Core dump from x86_64 binary (compiled in any way I tried) gives wrong stacktrace.
2. ARM binary compiled on x86_64 with "-O0 -g" coredumps straightaway (see stacktrace pointing to lj_vm.s:886 above)

The issue 2. worries me because if the ARM binary compiled with "-O0 -g" is "obviously bad" then who knows how "bad" will be the ARM binary compiled with the normal CFLAGS? Do you see what I mean now?

**Comment by tigran123** [comment]
You could (and should) ask "what about ARM binary compiled on FC17 32bit with "-O0 -g"? Does it coredump too?" I haven't tested this yet and now I have such terrible headache that it will wait until tomorrow :)

(I put in a personal log entry "what is the point of working so hard on KPV and not using it yourself?" --- so I'll do some reading for the rest of the evening :) Actually, reading _cures_ my headache, oddly enough --- for some people it makes headache worse)

**Comment by NiLuJe** [comment]
@tigran123 : Okay, much clearer, thanks :).

So, yeah, that's strange. It [the cross toolchain] should literally produce the exact same code, whether your build it on x86 or x86_64. The only variable that might throw a wrench in this is the JIT handling, which might do some weird stuff, but, still, that's weird...

I'd blame the wonky stacktraces on x86_64 (native, emu) on the JIT doing weird stuff too, that's potentially less scary, but still weird.

I'll check the debug builds on ARM thing, since my host is x86 ;).

**Comment by NiLuJe** [comment]
Oookay. Managed to at least reproduce the dimRect crash in EMU (x86), and I get a correct stacktrace. (On urantia, couldn't manage to crash anything on the russian bible (on master), but then I'm not familiar much with KPV, and I don't read russian, so that doesn't help :D).

FWIW:

```
Program received signal SIGSEGV, Segmentation fault.
0x080c0b6f in dimRect (L=0xb7fbc1c0) at blitbuffer.c:502
502                             *(dstptr+cx) =
(gdb) bt full
#0  0x080c0b6f in dimRect (L=0xb7fbc1c0) at blitbuffer.c:502
        dst = 0xb7b28770
        x = 794
        y = -407
        w = 30
        h = 22
        dstptr = 0xb725c10d ""
        cy = 9
        cx = 0
#1  0x081d43c7 in lj_BC_FUNCC ()
No symbol table info available.
#2  0x081bc0aa in lua_pcall (L=0xb7fbc1c0, nargs=0, nresults=-1, errfunc=0) at lj_api.c:1034
        g = 0xb7fbc1f0
        oldh = 0 '\000'
        ef = 0
        status = -1208237632
#3  0x080bd089 in main (argc=3, argv=0xbfffebf4) at kpdfview.c:74
        i = 3
```

Will check a debug ARM build now...

**Comment by NiLuJe** [comment]
Yup. Debug build segfaults on ARM when built on x86, too.

```
Core was generated by `./kpdfview ./reader.lua /mnt/us/documents'.
Program terminated with signal 11, Segmentation fault.
#0  0x001b379c in lj_BC_RET () at lj_vm.s:886
886             bl lj_state_growstack
(gdb) bt full
#0  0x001b379c in lj_BC_RET () at lj_vm.s:886
No locals.
#1  0x00193f90 in lua_pcall (L=0x402a91c0, nargs=0, nresults=-1, errfunc=0) at lj_api.c:1034
        g = 0x402a91f0
        oldh = 0 '\000'
        ef = 0
        status = 1076535864
#2  0x00071698 in main (argc=3, argv=0xbe99dd04) at kpdfview.c:74
        i = 3
```

Will check when built with another TC...

**Comment by NiLuJe** [comment]
Same crash with an ARM debug build built with my TC (... which happens to be 12MB smaller. GCC works in mysterious ways :D).

I'm stumped.

**Comment by tigran123** [comment]
@NiLuJe  Did you notice that mupdf overwrites our -fno-omit-frame-pointer with its own -fomit-frame-pointer when built with the "release" target anyway?

Also, you consider it obvious that the same TC 32bit binaries of gcc/etc should produce exactly the same executable code whether they are run on a 32bit or 64bit platform. I consider it not obvious at all because the experience tells me that running 32bit binaries on a 64bit platform (i.e. _emulating_ the i386 architecture on x86_64 architecture) cannot be made 100% reliable. Although it was many many years ago, when I wrote the SVR4 part of iBCS2 subsystem, I vaguely remember that we could never quite guarantee that sufficiently sophisticated UnixWare binaries (at the time I worked for SCO) would run flawlessly on Linux. The same applies to running Linux ia32 binaries on Linux x86_64 --- try running tux-math (my daughter's favourite Linux program :) on x86_64 to see how randomly and frequently it coredumps "for no apparent reason".

**Comment by tigran123** [comment]
@NiLuJe Just to add that I realize, of course, the importance of your finding that debug ARM binary coredumps in the same way when built with other TCs on a 32bit Linux. This makes it much less likely that building a non-debug ARM binary on a 64bit Linux will cause any problems. (not entirely 100% excluded, but extremely unlikely). Thanks!

**Comment by dpavlin** [comment]
I think I tracked this down by my favorite method - removing code. It seems that my change for centering page managed to interfere with rest of code, and it's not really needed.

**Comment by tigran123** [comment]
Congratulations... and you know what --- removing code is my FAVOURITE thing to do too! :)

**Comment by tigran123** [comment]
Oh, you have changed something now (as your PR is shown as mergeable) --- if so, I'll test it immediately.

**Comment by tigran123** [comment]
No, still pressing `Back` in `L` mode shifts the screen up if you are doing it in `Shift-S` mode. Tested on Russian Bible (Usletter-twocolumn layout).

UPDATE: wait, I forgot that you changed the .c files as well, so I need to recompile kpdfview. Wait, I'll do that.

UPDATE: No, even after recompiling the above comment about `Back` shifting the screen up still stands.

**Comment by dpavlin** [comment]
I can't reproduce this. My test scenario is:
- open `Russian-Synodal-Bible-USletter-twocolumn.pdf` in emulator
- `G` 3
- `Shift+S`
- `L`
- `back`

And screen doesn't shift for me.

**Comment by dpavlin** [comment]
If you ever merged older changes from this issue in your tree, that might be the problem becase git rebase rewrites all changes so you could have double commits...

**Comment by tigran123** [comment]
You have to press `Next` after `Shift-S` to see the problem.

**Comment by tigran123** [comment]
But I can re-test from scratch by creating a clean new dpavlin-screen-offset branch, if you wish.

**Comment by tigran123** [comment]
My scenario is this:
- open Russian Synodal Bible Usletter-twocolumn
- `G` 3
- `Shift-S`
- `Next`
- `L`
- `Back` --- the view shifted up

**Comment by tigran123** [comment]
Yes, you were right --- it was a double commit after rebase issue.
After creating a completely clean new branch, fetching and merging dpavlin/screen_offset into it the behaviour is completely different --- there are no visible links after pressing `Shift-S` and `Next` on the TOC pages of Russian Synodal Bible USletter-twocolumn.

I'll test on a few other files and will get back to you asap.

**Comment by tigran123** [comment]
Yes, testing on a plethora of files (both single and double-column) everything seems fine. You have fixed it! Merging the PR now.

**Comment by NiLuJe** [comment]
I was gonna say I couldn't reproduce the screen shifting either when I tested this the other day, but, eh, too late! ^^

@tigran123 : Nope, I didn't catch the frame-pointer trickery with mupdf, good catch! I'm still puzzled on the whole x86/x86_64 thing, though :D. But at least the crash on ARM debug build seems consistent, which, while not particularly a good thing, is somewhat reassuring ^^.

**Pull request merged**
