### PR TITLE
PaperWhite support for einkfb module

### PR DESCRIPTION
**Pull request by houqp**
Rewrite eink update method to support PaperWhite eink update.

### CODE REVIEW

**Comment by dpavlin** [comment]
@houqp eventually you will push me over the edge, and I will get PaperWhite just to see how our reader works on it. Fortunately Amazon doesn't seem to want to ship it to Croatia still, so I'm safe for now :-)

**Comment by tigran123** [comment]
@dpavlin I was tempted with exactly the same thoughts yesterday... We can already order it in the UK and I thought "ah, perhaps I should just get the WiFi version, just to test @houqp 's work on the paperwhite" :)
But it is still £139 for WiFi and £200 for 3G version (don't look at Amazon's prices as published --- they are deceptive, you have to include the price of the proper leather cover as well, of course). 

@houqp please tell me, is the screen really as bad as I predicted (by observing the "glowlight" feature of Nook Touch Glowlight I own)? Or is the use of the better screen underneath this stupid "light guiding layer" compensates enough to make the final result bearable, i.e. not much worse than Kindle 3?

**Comment by dpavlin** [comment]
http://www.youtube.com/watch?v=phO4QkHWsVE seem to show that it's different enough from alternative solution to be good

**Comment by houqp** [comment]
For anyone who is curious how the new ui branch looks like in PaperWhite, I uploaded a photo taken by my smartphoe ;P

http://www.flickr.com/photos/houqp/8109333525/in/photostream

@tigran123 , well, I have my kindle3's screen broken 1 month ago, so I cannot do a comparison here. So far I haven't read any book on PW yet, because the native reader sucks. The final result is bearable for me, but I might be wrong, because I cannot remember how good my kindle3's screen is ;p 

The only thing that I am not satisfied with is the built-in light. It is not evenly distributed as amazon's AD claimed... Most of the part is even, but the bottom line(about 10px) is not. But I won't use that feature often anyway ;p

**Comment by hwhw** [comment]
Just a note from a still too busy developer from the corner of the
playground: I've pre-ordered a PW - and it should arrive here on November,
22nd. There's hope for me getting my hands dirty when the winter arrives
here in Germany :-)

**Comment by NiLuJe** [comment]
I also have one (along with a K4 & Touch), so if you need one more guinea pig, I'm up ;).

**Comment by houqp** [comment]
@hwhw  cool! That should make the porting process much faster ;P

@NiLuJe , that will be great, we definitely need some one to test it on KTouch when the new UI framework is done :)

**Pull request merged**
