### PR TITLE
some of my fixes & merge lates changes from master branch

### PR DESCRIPTION
**Pull request by houqp**
- add render_mode support for djvu

### CODE REVIEW

**Comment by tigran123** [comment]
@houqp Btw, some of these changes are contained in the diff between my 99 and 114 builds which may have introduced a memory corruption.

**Comment by houqp** [comment]
OK. Is the corruption fixed now? It will be fine as long as the fixes in merged too. I just wanted to keep track of all your guys' commits :)

**Comment by tigran123** [comment]
@houqp the offending commit is the "fix kerning for Utf8Text family methods from tigran123" above or, rather, a part thereof. See the discussion in #401. The patch which undoes the corruption is SHA1: edd347eb55

**Comment by dpavlin** [comment]
@houqp will you merge all changes to this pull request or should we just merge it and have another one?

**Comment by tigran123** [comment]
@houqp just to confirm that my changes for kerning are not "offending" anymore. @hwhw has fixed the memory corruption properly --- it was NOT caused by my changes but was merely _triggered_ by them.

**Comment by houqp** [comment]
Ok, if that is the case, then it is ready for merge :)

**Pull request merged**
